% KNM1 confidence belt construction
% calculated or imported from data
% calculation and plotting takes place in RunSensitivity class
% Re-Analysis with updated model parameters + uncerainties
% Lisa Schlüter, 2021
%% settings
Mode        = 'FC';  % FC = Feldman Cousin, LT = Lokov Tkachov
Sensitivity = 'OFF'; % OFF= show best fit, ON = show sensitivity only
SavePlot    = 'OFF';

RunAnaArg = {'RunList','KNM1',...
    'DataType','Twin',...
    'fixPar','mNu E0 Norm Bkg',...%free par
    'exclDataStart',13,...
    'SysBudget',200,...
    'FSDFlag','KNM2_0p5eV',...
    'fitter','minuit',...
    'minuitOpt','min;migrad',...
    'NonPoissonScaleFactor',1.064,...
    'RadiativeFlag','ON',...
    'SynchrotronFlag','ON',...
    'AngularTF','ON',...
    'ELossFlag','KatrinT2A20',...
    'chi2','chi2CMShape',...
    'BKG_PtSlope', -2.2*1e-06,...
    'TwinBias_BKG_PtSlope',-2.2*1e-06,...
    'DopplerEffectFlag','FSD'};

% set up model 
D = MultiRunAnalysis(RunAnaArg{:});

%% re-init again
D = MultiRunAnalysis(RunAnaArg{:});
S = RunSensitivity('RunAnaObj',D);
%% Define Test values
mNuSq = 0;
%% Compute and Plot Confidence Belt
S.ConfLevel = 0.9; % confidence level (0==1 sigma)
switch Mode
    case 'FC'
        S.ComputeFC_Asimov('mNuSq_t',mNuSq,'nSamplesAsimov',300);
        S.PlotFCBelt('HoldOn','OFF','Sensitivity',Sensitivity,'SavePlot',SavePlot);
    case 'LT'
        S.ComputeLokhov_Asimov('mNuSq_t',mNuSq);
        S.PlotFCBelt('Lokov','ON','Sensitivity',Sensitivity,'SavePlot',SavePlot);
end

