% perform grid search in vicinity of best fit obtained from coarse fit

%% settings that might change
nGridSteps_BfImp = 25;
chi2 = 'chi2Stat';%CMShape';
DataType = 'Real';
nGridSteps_Old   = 40;
LoadGridArg = {'ExtmNu4Sq','OFF','mNu4SqTestGrid',5};
freePar = 'mNu E0 Norm Bkg';
range = 40;

%% configure RunAnalysis object
if strcmp(chi2,'chi2Stat')
    NonPoissonScaleFactor = 1;
elseif  strcmp(chi2,'chi2CMShape')
    NonPoissonScaleFactor = 1.112;
end
RunAnaArg = {'RunList','KNM2_Prompt',...
    'DataType',DataType,...
    'fixPar',freePar,...%free par
    'SysBudget',40,...
    'fitter','minuit',...
    'minuitOpt','min;migrad',...
    'RadiativeFlag','ON',...
    'FSDFlag','KNM2_0p5eV',...
    'ELossFlag','KatrinT2A20',...
    'AnaFlag','StackPixel',...
    'chi2',chi2,...
    'NonPoissonScaleFactor',NonPoissonScaleFactor,...
    'FSD_Sigma',sqrt(0.0124+0.0025),...
    'TwinBias_FSDSigma',sqrt(0.0124+0.0025),...
    'TwinBias_Q',18573.7,...
    'PullFlag',99,...;%99 = no pull
    'BKG_PtSlope',3*1e-06,...
    'TwinBias_BKG_PtSlope',3*1e-06,...
    'DopplerEffectFlag','FSD'};
A = MultiRunAnalysis(RunAnaArg{:});
%% configure Sterile analysis object
SterileArg = {'RunAnaObj',A,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',nGridSteps_Old,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',range,...
    'LoadGridArg',LoadGridArg};

S = SterileAnalysis(SterileArg{:});
S.LoadGridFile(S.LoadGridArg{:});
%%
% find grid point with smallest chi^2 (no interpolation!)
[row, col]    = find(S.chi2 == min(S.chi2(:)));
mNu4Sq_bf = S.mNu4Sq(col,1);
sin2T4_bf = S.sin2T4(1,row);

% construct grid around best fit
S.nGridSteps = nGridSteps_BfImp;
mNu4Sq = logspace(log10(S.mNu4Sq(col-1,1)),log10(S.mNu4Sq(col+1,1)),S.nGridSteps)'; % has to be nGridSteps x 1
sin2T4 = logspace(log10(S.sin2T4(1,row-1)),log10(S.sin2T4(1,row+1)),S.nGridSteps); % has to be 1 x nGridSteps

ExternalGrid = {mNu4Sq,sin2T4};
S.GridSearch('ExtGrid',ExternalGrid);


