% do with with best fit values for sin2t4 and m412, rest free

%% settings that might change
chi2 = 'chi2CMShape';
DataType = 'Real';

savedir = sprintf('%sksn2ana/ksn2_BestFit/results/',getenv('SamakPath'));
savefile = sprintf('%sksn2_BestFitPar_mNuE0NormBkg_%s_%s.mat',...
    savedir,DataType,chi2);
if exist(savefile,'file') 
    load(savefile)
else  
   % best fit from fine grid
   sin2T4_bf = 0.026742340546809;
   mNu4Sq_bf = 98.343698856109157;
    %% configure RunAnalysis object
    if strcmp(chi2,'chi2Stat')
        NonPoissonScaleFactor = 1;
    elseif  strcmp(chi2,'chi2CMShape')
        NonPoissonScaleFactor = 1.112;
    end
    RunAnaArg = {'RunList','KNM2_Prompt',...
        'DataType',DataType,...
        'fixPar','mNu E0 Norm Bkg',...%free par
        'SysBudget',40,...
        'fitter','minuit',...
        'minuitOpt','min;migrad',...
        'RadiativeFlag','ON',...
        'FSDFlag','KNM2_0p5eV',...
        'ELossFlag','KatrinT2A20',...
        'AnaFlag','StackPixel',...
        'chi2',chi2,...
        'NonPoissonScaleFactor',NonPoissonScaleFactor,...
        'FSD_Sigma',sqrt(0.0124+0.0025),...
        'TwinBias_FSDSigma',sqrt(0.0124+0.0025),...
        'TwinBias_Q',18573.7,...
        'PullFlag',99,...;%99 = no pull
        'BKG_PtSlope',3*1e-06,...
        'TwinBias_BKG_PtSlope',3*1e-06,...
        'DopplerEffectFlag','FSD'};
    A = MultiRunAnalysis(RunAnaArg{:});
    %%
    A.exclDataStart = A.GetexclDataStart(40);
    A.ModelObj.SetFitBiasSterile(mNu4Sq_bf,sin2T4_bf);
    A.Fit;
    FitResult = A.FitResult;
    %%
    save(savefile,'FitResult','mNu4Sq_bf','sin2T4_bf','RunAnaArg');
end
  