addpath(genpath('../../../Samak2.0'));

myEffects = struct(...
    'RF_EL','ON',...  % Response Function(RF) EnergyLoss
    'RF_BF','ON',...  % RF B-Fields
    'RF_RX','ON',...
    'FSD','ON',...
    'TASR','ON',...
    'TCoff_RAD','ON',...
    'TCoff_OTHER','ON',...
    'DOPoff','ON');  % RF Column Density, Cross Section

WGTS_CD_MolPerCm2_RelErr = 0.1;
MACE_Bmax_T_RelErr = 0.02;       % B-Fields
MACE_Ba_T_RelErr= 0.02;
WGTS_B_T_RelErr = 0.02;
ISXsection_RelErr = 0.02;        % Inelastic scattering(IS) cross section
WGTS_TASR_RelErr=0.023;         % Relative Error on subRun Tritium activity
FSDNorm_RelErr= 0.03;           % Normalization Error on ground state (sum of GS+ES probability is still always 100%)
FSDShape_RelErr= 0.03;

A = RunAnalysis('RunNr',40263,'AnaFlag','StackPixel');

A.ComputeCM('Mode','Compute','SysEffects',myEffects,...
    'WGTS_CD_MolPerCm2_RelErr',WGTS_CD_MolPerCm2_RelErr,...
    'MACE_Bmax_T_RelErr',MACE_Bmax_T_RelErr,...
    'MACE_Ba_T_RelErr',MACE_Ba_T_RelErr,...
    'WGTS_B_T_RelErr',WGTS_B_T_RelErr,...
    'ISXsection_RelErr',ISXsection_RelErr,...
    'WGTS_TASR_RelErr',WGTS_TASR_RelErr,...
    'FSDNorm_RelErr',FSDNorm_RelErr,'FSDShape_RelErr',FSDShape_RelErr);






