

Ranges = [40,90];
ROIFlag = '14keV';
parfor i=1:numel(Ranges)
    knm2_FitRunList(...
        'ROIFlag',ROIFlag,...
        'RunList','KNM2_Prompt',...
        'freePar','E0 Bkg Norm',...
        'Range',Ranges(i),...
        'MosCorrFlag','ON');
end