% show how contour shifts if global minum would be considered
% ksn2 chi2 grid - non physical parameter space 4 quadrants
% ksn2 plot chi2 grid search: 1 at a time to cross check
% 4 quadrants
%% settings that might change
chi2 = 'chi2CMShape';
DataType = 'Real';
nGridSteps = 30;
range = 40;

%% configure RunAnalysis object
if strcmp(chi2,'chi2Stat')
    NonPoissonScaleFactor = 1;
elseif  strcmp(chi2,'chi2CMShape')
    NonPoissonScaleFactor = 1.112;
end
RunAnaArg = {'RunList','KNM2_Prompt',...
    'DataType',DataType,...
    'fixPar','E0 Norm Bkg',...%free par
    'SysBudget',40,...
    'fitter','minuit',...
    'minuitOpt','min;migrad',...
    'RadiativeFlag','ON',...
    'FSDFlag','KNM2_0p5eV',...
    'ELossFlag','KatrinT2A20',...
    'AnaFlag','StackPixel',...
    'chi2',chi2,...
    'NonPoissonScaleFactor',NonPoissonScaleFactor,...
    'FSD_Sigma',sqrt(0.0124+0.0025),...
    'TwinBias_FSDSigma',sqrt(0.0124+0.0025),...
    'TwinBias_Q',18573.7,...
    'PullFlag',99,...;%99 = no pull
    'BKG_PtSlope',3*1e-06,...
    'TwinBias_BKG_PtSlope',3*1e-06,...
    'DopplerEffectFlag','FSD'};
A = MultiRunAnalysis(RunAnaArg{:});
%% configure Sterile analysis object
SterileArg = {... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',nGridSteps,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',range,...
    'LoadGridArg',{'ExtmNu4Sq','ON','mNu4SqTestGrid',5},...
    'InterpMode','lin'};
S = SterileAnalysis('RunAnaObj',A,SterileArg{:});

%%
% find global best fit (NW quadrant)
S.InterpMode = 'spline';
GridArg = {'NegmNu4Sq','OFF','Negsin2T4','ON','Extsin2T4','OFF'};
S.LoadGridFile(S.LoadGridArg{:},GridArg{:});
S.Interp1Grid('Maxm4Sq',36^2);
S.FindBestFit;
chi2_bf_NW = S.chi2_bf;

% load + plot physical region (NE quadrant)
S.InterpMode = 'Mix';
GridArg = {'NegmNu4Sq','OFF','Negsin2T4','OFF','Extsin2T4','ON'};
S.LoadGridFile(S.LoadGridArg{:},GridArg{:});
S.Interp1Grid('Maxm4Sq',36^2);
preg= S.ContourPlot('BestFit','ON');
chi2_bf_NE = S.chi2_bf;

S.chi2_ref = chi2_bf_NW;
pglobal = S.ContourPlot('BestFit','OFF','HoldOn','ON','Color',rgb('Orange'),'LineStyle','-.');

%% legend
leg = legend([preg,pglobal],...
     sprintf('\\chi^2_{min} = %.1f (global \\in physical region)',chi2_bf_NE),...
     sprintf('\\chi^2_{min} = %.1f (global)',chi2_bf_NW));
PrettyLegendFormat(leg);

plotname = [extractBefore(S.DefPlotName,'FSD'),'_QuadrantGlobalMin.pdf'];
export_fig(plotname);