
% fit twin and look at nu mass bias
% compare to expected bias from qU-variation

RunList = 'KNM1';
range   = 40;         % 40eV range = 27 subruns
% Init Model Object and covariance matrix object
T = MultiRunAnalysis('RunList',RunList,...
    'chi2','chi2Stat',...
    'DataType','Twin',...
    'fixPar','mNu E0 Norm Bkg',... free parameter
    'RadiativeFlag','ON',...
    'NonPoissonScaleFactor',1,...
    'minuitOpt','min ; minos',...
    'FSDFlag','Sibille',...
    'ELossFlag','KatrinT2',...
    'SysBudget',22,...
    'AngularTFFlag','OFF',...
    'DopplerEffectFlag','OFF');
T.exclDataStart = T.GetexclDataStart(range); 
T.Fit;


%%
B = RunAnalysis('RunNr',56160,'chi2','chi2Stat',...
    'DataType','Twin',...
    'fixPar','mNu E0 Norm Bkg',... free parameter
    'RadiativeFlag','ON',...
    'NonPoissonScaleFactor',1,...
    'minuitOpt','min ; minos',...
    'FSDFlag','Sibille',...
    'ELossFlag','KatrinT2',...
    'SysBudget',22,...
    'AngularTFFlag','OFF',...
    'DopplerEffectFlag','OFF');
B.exclDataStart = B.GetexclDataStart(range); 
B.Fit;
