% Test SterileAnalysis class
% Lisa, May2020
% plot qU Scan
% fixed parameter
%% settings for runanalysis
DataType = 'Real';
%%
RunAnaArg = {'RunList','KNM1',...
    'fixPar','E0 Norm Bkg',...
    'DataType',DataType,...
    'FSDFlag','SibilleFull',...
    'ELossFlag','KatrinT2',...
    'AnaFlag','StackPixel',...
    'chi2','chi2Stat',...
    'ROIFlag','Default',...
    'SynchrotronFlag','ON',...
    'AngularTFFlag','OFF',...
    'ISCSFlag','Edep',...
    'TwinBias_Q',18573.73,...
    'SysBudget',24,...
    'pullFlag',99,...
    'NonPoissonScaleFactor',1};

T = MultiRunAnalysis(RunAnaArg{:});
T.chi2 = 'chi2CMShape';
%% settings sterile class
SterileArg = {'RunAnaObj',T,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',50,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',65};

S = SterileAnalysis(SterileArg{:});
%%
S.RunAnaObj.DataType = 'Twin';
S.ConfLevel = 95;
S.range = 65;
switch S.RunAnaObj.DataType
    case 'Real'
        Arg = {'SavePlot','png'}; 
        S.InterpMode = 'spline';
    case 'Twin'
         Arg = {'SavePlot','png'};%,41,40]};
           S.InterpMode = 'spline';
end
%S.LoadGridFile;
%S.Interp1Grid('RecomputeFlag','ON');
%S.GridPlot('BestFit','OFF','Contour','OFF');
S.PlotFitriumSamak(Arg{:},'PlotStat','ON');
 
