A=RelicNuDebug('Params','KNM1');
%A.Chi2Twin('Recompute','OFF','Plot','ON','Syst','ON');
%A.Chi2Twin('Recompute','OFF','Plot','ON','Syst','OFF');
%fig1=figure(1);
%A.SystBreakdown('TwinBias_mnuSq',0);
%fig2=figure(2);
%A.SystBreakdown('TwinBias_mnuSq',1);
%fig3=figure(3);
%A.SystBreakdown('TwinBias_mnuSq',5);
A.Chi2Scan_2D('Netabins',10,'Nmnubins',10)