%
% FitVFT1
% 19/05/18
% T. Lasserre
%

clear all

% Model
A = ref_run40257;
A.ComputeTBDDS();
A.ComputeTBDIS();

% Covariance Matrix
myEffects = struct(...
    'RF_EL','ON',...   % Response Function(RF) EnergyLoss
    'RF_BF','ON',...   % RF B-Fields
    'RF_RX','ON',...   % RF Column Density, Cross Section
    'TCoff','ON',...   % Activity Fluctuations
    'FSD','ON',...     % Activity Fluctuations
    'TASR','ON');      % FSD

C = CovarianceMatrix('StudyObject',A,...
    'nTrials',1000,...
    'RunFlag','OFF', 'nRuns',1,...
    'SysEffect',myEffects,...
    'RecomputeFlag','OFF',...
    'MACE_Ba_T_RelErr',1e-2,  ...
    'MACE_Bmax_T_RelErr',1e-2,  ...
    'WGTS_B_T_RelErr',1e-2,  ...
    'WGTS_CD_MolPerCm2_RelErr',0.1, ...
    'ISXsection_RelErr',1e-2,  ...
    'RecomputeFlag','ON',  ...
    'WGTS_TASR_RelErr',1e-2,  ...
    'FSDNorm_RelErr',3e-2,  ...
    'FSDShape_RelErr',3e-2,  ...
    'BM1_RatePerSec',0.3);

C.ComputeCM_FSD;
C.ComputeCM_RF;
C.ComputeCM_TASR;
C.ComputeCM;
imagesc(C.CovMatFrac)
covmat=C.CovMat;
covmatfrac=C.CovMatFrac;
save('CM_VFTRUN40257_10percent.mat','covmat','covmatfrac');