% fit knm1 run list (again) with stat + NonPoisson

% KNM1 Final fit Results
% Uniform Fit
% Golden Run List
% Golden Pixel List
%% settings
RunList = 'KNM1';
range   = 40;         % 40eV range = 27 subruns
% Init Model Object and covariance matrix object
Real = MultiRunAnalysis('RunList',RunList,...
    'chi2','chi2Stat',...
    'DataType','Real',...
    'fixPar','E0 Norm Bkg',... free parameter
    'RadiativeFlag','ON',...
    'NonPoissonScaleFactor',1.064,...
    'minuitOpt','min ; minos',...
    'FSDFlag','Sibille0p5eV',...
    'ELossFlag','KatrinT2',...
    'AngularTFFlag','OFF');
Real.exclDataStart = Real.GetexclDataStart(range); 
Real.FitRunList;

