% ksn2 calculate chi2 grid search
%% settings that might change
nGridSteps            = 50;
DataType              = 'Real';
range                 = 40;
chi2                  = 'chi2CMShape';
freePar               = 'E0 Norm Bkg';
%% configure RunAnalysis object
if strcmp(chi2,'chi2Stat')
    NonPoissonScaleFactor = 1;
elseif  strcmp(chi2,'chi2CMShape')
    NonPoissonScaleFactor = 1.064;
end
Real = MultiRunAnalysis('RunList','KNM1',...
    'chi2',chi2,...
    'DataType',DataType,...
    'fixPar',freePar,...
    'NonPoissonScaleFactor',NonPoissonScaleFactor,...
    'SysBudget',200,...
    'minuitOpt','min ; minos',...
    'FSDFlag','KNM2_0p1eV',...
    'ELossFlag','KatrinT2A20',...
    'AngularTFFlag','ON',...
    'SynchrotronFlag','ON',...
    'RadiativeFlag','ON',...
    'DopplerEffectFlag','FSD',...
    'BKG_PtSlope',-2.2*1e-06);
Real.exclDataStart = Real.GetexclDataStart(range);
%% configure Sterile analysis object
SterileArg = {'RunAnaObj',Real,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',nGridSteps,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',range};

S = SterileAnalysis(SterileArg{:});
S.GridSearch('ExtmNu4Sq','OFF','mNu4SqTestGrid',2);


%% new for ringberg slides
S.LoadGridFile('ExtmNu4Sq','OFF','mNu4SqTestGrid',2);
S.Interp1Grid;

[legHandle,legStr] = S.ContourPlotOsci('DayaBay','ON','DoubleChooz','ON','SavePlot','OFF','Style','PRL','BestFit','ON','Color',rgb('SkyBlue'));

hold on;

pNone1  = plot(NaN,NaN,'w.');
pNone2  = plot(NaN,NaN,'w.');
legStr{end} = sprintf('KATRIN 1^{st} at 95%% C.L.');
leg = legend([legHandle{:},pNone1,pNone2],{legStr{:}, sprintf('KATRIN 2^{nd} at 95%% C.L.'),...
    sprintf('KATRIN 1^{st}+2^{nd} at 95%% C.L.')},'EdgeColor','none','Location','northoutside');

leg.FontSize = 16;
PrettyFigureFormat

pltdir = [getenv('SamakPath'),'ksn2ana/ksn2_OtherExp/plots/'];
pltname1 = sprintf('%sksn2_RingbergPlt_KSN1.png',pltdir);
print(gcf,pltname1,'-dpng','-r350');
%%


%% settings that might change
chi2 = 'chi2CMShape';
DataType = 'Twin';
nGridSteps = 40;
range = 40;
freePar = 'E0 Norm Bkg';
%% configure RunAnalysis object
if strcmp(chi2,'chi2Stat')
    NonPoissonScaleFactor = 1;
elseif  strcmp(chi2,'chi2CMShape')
    NonPoissonScaleFactor = 1.112;
end
RunAnaArg = {'RunList','KNM2_Prompt',...
    'DataType',DataType,...
    'fixPar',freePar,...%free par
    'SysBudget',40,...
    'fitter','minuit',...
    'minuitOpt','min;migrad',...
    'RadiativeFlag','ON',...
    'FSDFlag','KNM2_0p5eV',...
    'ELossFlag','KatrinT2A20',...
    'AnaFlag','StackPixel',...
    'chi2',chi2,...
    'NonPoissonScaleFactor',NonPoissonScaleFactor,...
    'FSD_Sigma',sqrt(0.0124+0.0025),...
    'TwinBias_FSDSigma',sqrt(0.0124+0.0025),...
    'TwinBias_Q',18573.7,...
    'PullFlag',99,...;%99 = no pull
    'BKG_PtSlope',3*1e-06,...
    'TwinBias_BKG_PtSlope',3*1e-06,...
    'DopplerEffectFlag','FSD'};
A = MultiRunAnalysis(RunAnaArg{:});
%% configure Sterile analysis object
SterileArg = {'RunAnaObj',A,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',nGridSteps,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',range,...
    'LoadGridArg',{'ExtmNu4Sq','ON','mNu4SqTestGrid',2}};

%
S = SterileAnalysis(SterileArg{:});
S.nGridSteps = 30;
S.LoadGridFile(S.LoadGridArg{:});
S.Interp1Grid;
            %%
pKnm2 = S.ContourPlotOsci('HoldON','ON','Color',rgb('DodgerBlue'),'RAA','OFF','Mainz','OFF','Neutrino4','OFF',...
    'Prospect','OFF','DayaBay','OFF','DoubleChooz','OFF','Stereo','OFF');

%%
hold on;
% load combi fixed m_nu
savedir_fix = [getenv('SamakPath'),'ksn2ana/ksn2_RunCombination/results/'];
savefile_fix = sprintf('%sksn21_Combination_ReAna_%s.mat',savedir_fix,DataType);

% load file
if exist(savefile_fix,'file') 
    dfix = importdata(savefile_fix);
    fprintf('load results from file %s \n',savefile_fix)
else
     fprintf('load results from file %s \n',savefile_fix)
    return
end

mNu4Sq_fix   = dfix.mNu4Sq_contour_12;
sin2T4Sq_fix  = 4*dfix.sin2T4_contour_12.*(1-dfix.sin2T4_contour_12);

%% plot
hold on;
pfix = plot(sin2T4Sq_fix,mNu4Sq_fix,':','Color',rgb('Navy'),'LineWidth',2.5);
%%
legStrNew = {legStr{:},...
    sprintf('KATRIN 2^{nd} at 95%% C.L.'),...
    sprintf('KATRIN 1^{st}+2^{nd} at 95%% C.L.')};
legHandleNew = [{legHandle{:},pKnm2{1},pfix}];
legend([legHandleNew{:}],...
   legStrNew{:},...
    'EdgeColor','none','Location','northoutside');

leg.FontSize = 16;
PrettyFigureFormat

pltname2 = sprintf('%sksn2_RingbergPlt_KSN12.png',pltdir);
print(gcf,pltname2,'-dpng','-r350');
