% Parameters
nRun = 10;

%% Fake Run Generation
% Create Fake Runs
% F.CleanFakeRuns; F.CleanFakeRunsTD
F=FakeRunsGenerator(...
    'RefKATRINconfig','KITNuScan','FakeRunType','FakeKITNuScan',...
    'NumberOfRuns',nRun,'SCLinearDrift','ON',...
    'FakeRunPath','../../tritium-fakedata/mat',...
    'Asimov','OFF');
F.DrawFakeRunsTBDIS_Uniform;
F.SaveFakeRuns; F.SaveFakeRunsTD;
%% Plots
% Column Density
stairs(F.WGTS_CD_MolPerCm2_LuT); PrettyFigureFormat
% TBDIS - 1 run
%F.SimFakeObj_LuT{5}.PlotTBDIS('CPS','ON','type','log')

%% Analyze Data
M=MultiRunAnalysis('DataType','Fake','FakeRunType','FakeKITNuScan','RunList','KITNUSCAN','exclDataStart',2,'fixPar','1 5 6','chi2','chi2Stat','Debug','ON','ELossFlag','Abdurashitov');
%% Systematics
M.chi2='chi2CMShape';
systematics = struct(...
    'RF_EL','ON',...
    'RF_BF','ON',...
    'RF_RX','ON',...
    'FSD','ON',...
    'TASR','ON',...
    'TCoff_RAD','ON',...
    'TCoff_OTHER','ON',...
    'DOPoff','OFF');
CMoptions   = {
    'WGTS_TASR_RelErr',0.005,...
    'FSDNorm_RelErr',0.01,...
    'FSDShapeGS_RelErr',0.04,...
    'FSDShapeES_RelErr',0.18,...
    'MACE_Ba_T_RelErr',0.01,...
    'MACE_Bmax_T_RelErr',0.002,...
    'WGTS_B_T_RelErr',0.025,...
    'WGTS_CD_MolPerCm2_RelErr',0.02,...
    'ISXsection_RelErr',0.02,...
    'BkgCM','OFF',...
    'Stack','OFF'...
    };
M.ComputeCM('RecomputeFlag','OFF','SysEffects',systematics,CMoptions{:});

%%
M.chi2 = 'chi2Stat';
M.ModelObj.E0_bias=0;
M.ModelObj.Bkg_Bias=0;
M.ModelObj.Norm_Bias=0;
M.ModelObj.mnuSq_Bias=0;
M.Fit; 
%M.PlotFit('Mode','Rate');

%M.FitRunList('Recompute','ON');
