function f = TestFuncJacob(p,A)
if numel(p)<5
    p(5)=0; p(6)=0;
end
if numel(p)<6
    p(6)=0;
end
A.ComputeTBDDS(...
    'mSq_bias',p(1),...
    'E0_bias',p(2),...
    'B_bias',p(3),...
    'N_bias',p(4),...
    'DTGS_bias',p(5),...
    'DTES_bias',p(6)); 
A.ComputeTBDIS();
f = A.TBDIS;
end