qURange  = [95,20];
RunList = 'KNM1';
DataType = 'Real';
chi2 = 'chi2Stat';
SysBudet = 22;
fixPar = 'mNu E0 Norm Bkg';% free par
FSDFlag       = 'SibilleFull';
ELossFlag     = 'KatrinT2';
AngularTFFlag = 'OFF';

M = MultiRunAnalysis('RunList',RunList,...
    'chi2','chi2Stat',...
    'DataType',DataType,...
    'fixPar',fixPar,...
    'RadiativeFlag','ON',...
    'NonPoissonScaleFactor',1.064,...
    'minuitOpt','min ; migrad',...
    'FSDFlag',FSDFlag,...
    'ELossFlag',ELossFlag,...
    'SysBudget',22,...
    'AngularTFFlag',AngularTFFlag);

M.chi2 = chi2;
%% systematics
if strcmp(chi2,'chi2CMShape')
    if strcmp(fixPar,'5 6 7 8 11')
        M.ComputeCM('FSDNorm_RelErr',0);
    else
        M.ComputeCM;
    end
end
%%

M.ModelObj.AngularTFFlag = 'OFF';
M.ModelObj.ELossFlag = 'KatrinT2';
if strcmp(M.ModelObj.AngularTFFlag,'ON')
    AddsaveStr = sprintf('_AngTF_%s',M.ModelObj.ELossFlag);
else
    AddsaveStr = sprintf('_%s',M.ModelObj.ELossFlag);
end
[~,~,~,~,pPRL] = ...
    M.qUScan('qURange',qURange,...
    'saveplot','OFF',...
    'RecomputeFlag','OFF',...
    'CorrMean','OFF',...
    'HoldOn','ON1',...
    'RelFlag','OFF',...
    'saveStr',AddsaveStr,...
    'RefLine',40);

M.ModelObj.AngularTFFlag = 'ON';
M.ModelObj.ELossFlag = 'KatrinT2A20';
if strcmp(M.ModelObj.AngularTFFlag,'ON')
    AddsaveStr = sprintf('_AngTF_%s',M.ModelObj.ELossFlag);
else
    AddsaveStr = sprintf('_%s',M.ModelObj.ELossFlag);
end

[~,~,~,~,pNew] = ...
    M.qUScan('qURange',qURange,...
    'saveplot','OFF',...
    'RecomputeFlag','OFF',...
    'CorrMean','OFF',...
    'HoldOn','ON',...
    'RelFlag','OFF',...
    'saveStr',AddsaveStr,...
    'RefLine','OFF');

leg = legend([pPRL,pNew],sprintf('PRL model'),...
    sprintf('New model: KNM2 e-loss & NITF'),...
    'Location','southwest','EdgeColor',rgb('Silver'),...
    'FontSize',get(gca,'FontSize'));

ylim([-3 0.8])

savedir = [getenv('SamakPath'),'knm1ana/knm1_qUScan/plots/'];
freeParStr = ConvertFixPar('Mode','Reverse','freePar',M.fixPar);
savename = [savedir,sprintf('qUScan_%s_1_%s_%sNP%.3f_FitPar%s_%.0feV-%.0feV_%s%s.png',...
    M.RunData.RunName,M.DataType,M.chi2,M.NonPoissonScaleFactor,freeParStr,...
    qURange(1),qURange(2),M.FSDFlag,'_ComparePRLmodel')];
print(gcf,savename,'-dpng','-r450');