function chi2 = KrLineChi2_sat(p,X)
%
% Chi2 Function For Fit Krypton Spectrum
% With Nuisance Parameters
% 
% Th. Lasserre, 2017
%
% Gaussian Xi2
% X = [ "column vector of bin centers"  | "column vector of data" | "column vector of uncertainties" | "... extra info" ]
% p = [ p1; p2; ... ] column vector of parameter to fit

nn = X(:,2)~=0; % indexes of non-null bins
x  = X(nn,1);    % bin centers of non-null bins
y  = X(nn,2);    % bin content of non-null bins
z  = X(nn,3);    % uncertainties bin content of non-null bins
m  =  KrLineModel7par_sat(p);

% Poisson deviance chi square.
% chi2 = -2*sum( y(1:numel(x)) - m(1:numel(x)) + y(1:numel(x)).*log(m(1:numel(x))./y(1:numel(x))) );                      

% Gaussian
chi2 = sum(( y(1:numel(x)) - m(1:numel(x))).^2 ./ z(1:numel(x)).^2);
%disp(chi2);
% ...
%       + (p(2)/1e-6)^2 ...
%       + (p(3)/1e-6)^2 ...
%       + (p(4)/1e-6)^2;
%          
%     + (p(8)/aQEDe)^2 ...
%     + (p(9)/aRecCorre)^2 ...
%     + (p(10)/aECorre)^2 ...
%     + (p(11)/aCCorre)^2 ...
%     + (p(12)/aL0Corre)^2 ...
%     + (p(13)/aQCorre)^2 ...
%     + (p(14)/aSCorre)^2 ...
%     + (p(15)/aGSe)^2 ...
%     + (p(16)/aESe)^2 ...
%     + ((p(15)+p(16))/1e-10)^2 ...
%     + (p(17)/aQOffe)^2 ...
%     + (p(19)/aRbkgOffe)^2;

end