% KNM2 twin multi ring fit
% March 2020, Lisa

RunList = 'KNM2_Prompt';
E0 = knm2FS_GetE0Twins('SanityPlot','OFF');
range = 40;
chi2 = 'chi2CMShape';
pullFlag = 4;
freePar = 'mNu E0 Norm Bkg';
DataType = 'Twin';
RingMerge = 'Full';

savedir = [getenv('SamakPath'),'knm2ana/knm2_MultiRingFit/results/'];
MakeDir(savedir);
savename = [savedir,sprintf('knm2_MultiRingFit_%s_%s_%s_%s_pull%.0f_%.0feVrange_RingMerge%s.mat',...
    DataType, RunList,chi2,strrep(freePar,' ',''),pullFlag,range,RingMerge)];

% read data and set up model
RunArg = {'RunList',RunList,...
    'chi2',chi2,...
    'DataType',DataType,...
    'fixPar',freePar,...
    'RadiativeFlag','ON',...
    'minuitOpt','min',...
    'FSDFlag','BlindingKNM2',...
    'ELossFlag','KatrinT2',...
    'SysBudget',33,...
    'AnaFlag','Ring',...
    'RingMerge',RingMerge,...
    'chi2','chi2Stat',...
    'pullFlag',pullFlag,...
    'TwinBias_Q',E0,...
    'ROIFlag','14keV',...
    'MosCorrFlag','OFF',...
    'NonPoissonScaleFactor',1};

MR = MultiRunAnalysis(RunArg{:});
MR.exclDataStart = MR.GetexclDataStart(range);
if ~strcmp(chi2,'chi2Stat')
    MR.NonPoissonScaleFactor = 1.112;
    MR.SetNPfactor; % convert to right dimension (if multiring)
    MR.chi2 = chi2;
    MR.ComputeCM;
end
MR.ModelObj.RFBinStep = 0.02;
MR.ModelObj.InitializeRF;
MR.Fit('CATS','ON','SaveFit','ON');
FitResults = MR.FitResult;
save(savename,'FitResults','RunArg','MR');
