% plot contour
% neutrino mass fixed to 0 eV^2
% neutrino mass fixed to best fit (-0.98 eV^2)
% 40 eV range

%Default KSN1 settings
RunAnaArg = {'RunList','KNM1',...
    'fixPar','E0 Norm Bkg',...
    'DataType','Real',...
    'FSDFlag','SibilleFull',...
    'ELossFlag','KatrinT2',...
    'AnaFlag','StackPixel',...
    'chi2','chi2Stat',...
    'ROIFlag','Default',...
    'SynchrotronFlag','ON',...
    'AngularTFFlag','OFF',...
    'ISCSFlag','Edep',...
    'TwinBias_Q',18573.73,...
    'SysBudget',24,...
    'pullFlag',99,...
    'NonPoissonScaleFactor',1.064};

A = MultiRunAnalysis(RunAnaArg{:});
A.chi2 = 'chi2CMShape';
% 2. SterileAnalysis class
SterileArg = {'RunAnaObj',A,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',50,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',40};
S = SterileAnalysis(SterileArg{:});
%%
S.RunAnaObj.ModelObj.mnuSq_i = 0;
S.RunAnaObj.fixPar = 'mNu E0 Norm Bkg';
S.RunAnaObj.InitFitPar;
S.InterpMode = 'lin';
S.LoadGridFile;
S.Interp1Grid;
pmU_free = S.ContourPlot('BestFit','ON','SavePlot','OFF','Color',rgb('Gray'),'LineStyle',':','HoldOn','OFF');

S.RunAnaObj.fixPar = 'E0 Norm Bkg';
S.RunAnaObj.InitFitPar;
S.InterpMode = 'spline';
S.RunAnaObj.ModelObj.mnuSq_i = 0;
S.LoadGridFile;
S.Interp1Grid;
pmU0eV2 = S.ContourPlot('BestFit','ON','SavePlot','OFF','Color',rgb('DodgerBlue'),'LineStyle','-','HoldOn','ON');

S.RunAnaObj.ModelObj.mnuSq_i = -0.98;
S.LoadGridFile;
S.Interp1Grid;
pmU_bf = S.ContourPlot('BestFit','ON','SavePlot','OFF','Color',rgb('Orange'),'LineStyle','-.','HoldOn','ON');


%% legend
leg = legend([pmU0eV2,pmU_bf,pmU_free],...
    sprintf('{\\itm}^2_\\nu = 0 eV^2'),...
    sprintf('{\\itm}^2_\\nu = -1 eV^2'),...
    sprintf('{\\itm}^2_\\nu free') );
leg.Title.String = sprintf('%s - %.0f eV range - %.0f%% C.L.',...
    S.GetPlotTitle('Mode','data'),S.range,S.ConfLevel);
leg.Title.FontWeight = 'normal';
legend boxoff
title('');
ylim([1 2e3]);
xlim([4e-03,0.5])


plotname = [extractBefore(S.DefPlotName,'FixmNuSq'),'_mNuSqFix_bf'];
print([plotname,'.png'],'-dpng','-r450');
export_fig([plotname,'.pdf']);
