% Script to develop and test multi ring fit
% based on KNM2 runs
% October 2019, Lisa

RunList = 'KNM1';

exclDataStart= 14;
chi2 = 'chi2CMShape';

% read data and set up model 
CommonArg = {'RunList',RunList,...
    'chi2','chi2Stat','DataType','Real',...
    'exclDataStart',exclDataStart,...
    'fixPar','mNu Norm E0 Bkg qU mTSq',...
    'RadiativeFlag','ON',...
    'minuitOpt','min ; minos',...
    'FSDFlag','Sibille0p5eV',...
    'ELossFlag','KatrinT2',...
    'SysBudget',22,...
    'AnaFlag','Ring',...
    'RingMerge','Full',...
    'pullFlag',[4 8],...
    'NonPoissonScaleFactor',[1.064 1.064 1.064 1.064],...
    'chi2',chi2};

R = MultiRunAnalysis(CommonArg{:});
%R.fixPar = 'fix 11 ;fix 12 ;fix 13 ;fix 14 ;fix 15 ;fix 16 ;fix 17 ;fix 18 ;fix 19 ;fix 20 ;fix 21 ;';
R.Fit;