
RunAnaArg = {'RunList','KNM2_Prompt',...
    'DataType','Twin',...
    'fixPar','E0 Norm Bkg',...%free par
    'SysBudget',40,...
    'fitter','minuit',...
    'minuitOpt','min;migrad',...
    'RadiativeFlag','ON',...
    'FSDFlag','KNM2_0p1eV',...
    'ELossFlag','KatrinT2A20',...
    'AnaFlag','StackPixel',...
    'chi2','chi2Stat',...
    'NonPoissonScaleFactor',1,...
    'FSD_Sigma',sqrt(0.0124+0.0025),...
    'TwinBias_FSDSigma',sqrt(0.0124+0.0025),...
    'TwinBias_Q',18573.7,...
    'PullFlag',99,...;%99 = no pull
    'BKG_PtSlope',3*1e-06,...
    'TwinBias_BKG_PtSlope',3*1e-06,...
    'DopplerEffectFlag','FSD'};
A = MultiRunAnalysis(RunAnaArg{:});

WGTS_CD_MolPerCm2_i = A.ModelObj.WGTS_CD_MolPerCm2;

%% isprob regular
A.ModelObj.KTFFlag = 'WGTSMACE';
A.ModelObj.WGTS_CD_MolPerCm2 = WGTS_CD_MolPerCm2_i;
[isprob_reg,Pis_z_reg]    = A.ModelObj.ComputeISProb('Method','Exact');

%% isprob 2x column density
A.ModelObj.KTFFlag = 'WGTSMACE';
A.ModelObj.WGTS_CD_MolPerCm2 = 2.*WGTS_CD_MolPerCm2_i;
[isprob_regx2,Pis_z_regx2]    = A.ModelObj.ComputeISProb('Method','Exact');

%% isprob
A.ModelObj.KTFFlag = 'RW_WGTSMACE';
A.ModelObj.WGTS_CD_MolPerCm2 = WGTS_CD_MolPerCm2_i;
[isprob_rw,Pis_z_rw]    = A.ModelObj.ComputeISProb('Method','Exact');
%% plot
z = linspace(0,9.9,1e2);
GetFigure;
Scat = 1;
preg = plot(-z/max(z)*10,Pis_z_reg(Scat,z),'LineWidth',2,'Color',rgb('DodgerBlue'));
hold on;
%preg0x2 = plot(-z/max(z)*10,Pis_z_regx2(0,z),'-.','LineWidth',2,'Color',rgb('DodgerBlue'));
px2 = plot(-z/max(z)*10,Pis_z_regx2(Scat,z),'-.','LineWidth',2,'Color',rgb('Orange'));

PrettyFigureFormat;
xlabel('Starting position WGTS (m)')
xticklabels({'0','1','2','3','4','5','6','7','8','9','10'});
ylabel('Scattering probability')
leg =legend([preg,px2],sprintf('\\rhod = %.1f\\cdot10^{17} mol/cm^2 \\rightarrow Integral: %.1f %%',WGTS_CD_MolPerCm2_i*1e-17,isprob_reg(Scat+1)),...
    sprintf('\\rhod = %.1f\\cdot10^{17} mol/cm^2 \\rightarrow Integral: %.1f %%',2*WGTS_CD_MolPerCm2_i*1e-17,isprob_regx2(Scat+1)),...
    'Location','southwest');
leg.Title.String = sprintf('%.0f \\times scattering',Scat);
leg.Title.FontWeight = 'normal';
PrettyLegendFormat(leg);
