% ksn2: all systematics minus 1 effects

MinusSysEffect = 'BkgPT';
%% settings that might change
chi2 = 'chi2Stat';
DataType = 'Twin';
nGridSteps = 30;
range = 40;
%% configure RunAnalysis object
RunAnaArg = {'RunList','KNM2_Prompt',...
    'DataType',DataType,...
    'fixPar','E0 Norm Bkg',...%free par
    'SysBudget',40,...
    'fitter','minuit',...
    'minuitOpt','min;migrad',...
    'RadiativeFlag','ON',...
    'FSDFlag','KNM2_0p5eV',...
    'ELossFlag','KatrinT2A20',...
    'AnaFlag','StackPixel',...
    'chi2',chi2,...
    'NonPoissonScaleFactor',1,...
    'FSD_Sigma',sqrt(0.0124+0.0025),...
    'TwinBias_FSDSigma',sqrt(0.0124+0.0025),...
    'TwinBias_Q',18573.7,...
    'PullFlag',99,...;%99 = no pull
    'BKG_PtSlope',3*1e-06,...
    'TwinBias_BKG_PtSlope',3*1e-06,...
    'DopplerEffectFlag','FSD'};
A = MultiRunAnalysis(RunAnaArg{:});
%% configure Sterile analysis object
if strcmp(DataType,'Real')
    LoadGridArg = {'mNu4SqTestGrid',5,'ExtmNu4Sq','ON'};
else
    LoadGridArg = {'mNu4SqTestGrid',5};
end

SterileArg = {'RunAnaObj',A,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',nGridSteps,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',range,...
    'LoadGridArg',LoadGridArg};

%%
S = SterileAnalysis(SterileArg{:});
S.RunAnaObj.chi2 = 'chi2CMShape';
if strcmp(MinusSysEffect,'NP')
    S.RunAnaObj.NonPoissonScaleFactor = 1;
    S.SysEffect = 'all';
elseif strcmp(MinusSysEffect,'BkgPT')
    S.RunAnaObj.NonPoissonScaleFactor = 1.112;
    S.SysEffect = 'allmBkgPT';
end

S.GridSearch(S.LoadGridArg{:});

