F = MultiRunAnalysis('RunList','KNM1',... % runlist defines which runs are analysed -> set MultiRunAnalysis.m -> function: GetRunList()
     'chi2','chi2CMShape',...                 % uncertainties: statistical or stat + systematic uncertainties
     'DataType','Twin',...                 % can be 'Real' or 'Twin' -> Monte Carlo
     'fixPar','mNu E0 Norm Bkg',...                   % free Parameter!!
     'RadiativeFlag','ON',...              % theoretical radiative corrections applied in model
     'NonPoissonScaleFactor',1.064,...     % background uncertainty are enhanced
     'fitter','minuit',...
     'minuitOpt','min ; minos',...         % technical fitting options (minuit)
     'FSDFlag','SibilleFull',...          % final state distribution
     'ELossFlag','KatrinT2',...            % energy loss function
     'SysBudget',24,...                    % defines syst. uncertainties -> in GetSysErr.m;
     'DopplerEffectFlag','FSD',...
     'Twin_SameCDFlag','OFF',...
     'Twin_SameIsotopFlag','OFF',...
     'SynchrotronFlag','ON',...
     'AngularTFFlag','OFF',...
     'TwinBias_Q',18573.73,...
     'TwinBias_mnuSq',1,...
     'TwinBias_WGTS_CD_MolPerCm2',0);