saveplot='OFF';

% load('./RelicNuBkg/Refs/RefsFromHeizmannPhD.mat');
% load('./RelicNuBkg/SensVsMnuSq_KNM1_[0_4].mat');
% eta=Sensitivities;
% mnuSq=sqrt(ScanPoints);
% load('./RelicNuBkg/SensVsMnuSq_TDR_[0_4].mat');
% Faes13     = importdata('RelicNuBkg/Refs/Fäs13.txt');
% LVV08lower = importdata('RelicNuBkg/Refs/LVV08lower.txt');
% LVV08upper = importdata('RelicNuBkg/Refs/LVV08upper.txt');
% RW04lower  = importdata('RelicNuBkg/Refs/RW04lower.txt');
% RW04upper  = importdata('RelicNuBkg/Refs/RW04upper.txt');
% HM05  = [HM05 HM05];
% KFM10 = [KFM10 KFM10];
% Lob99 = [Lob99 Lob99];
% Rob91 = [Rob91 Rob91];
% %area(linspace(-sqrt(2),2,2),Lob99,1e16,'FaceColor',[0 0.75 0.75]);
% fig1=figure('Renderer','painters');
% set(fig1, 'Units', 'normalized', 'Position', [0.001, 0.001,0.6, 0.6]);
% hold on;
% area(linspace(-sqrt(2),2,2),HM05,1e16,'FaceColor',[0 0.5 0.5]);
% area(linspace(-sqrt(2),2,2),Rob91,'FaceColor',[0 0.25 0.25]);
% plot(mnuSq,eta,'LineWidth',3,'Color','red');
% plot(sqrt(ScanPoints),Sensitivities,'LineWidth',3,'Color','red','LineStyle',':');
% plot(linspace(-sqrt(2),2,2),KFM10,'LineWidth',2);
% plot(Faes13(:,1),Faes13(:,2),'LineWidth',2,'LineStyle','--');
% plot(LVV08lower(:,1),LVV08lower(:,2));
% plot(LVV08upper(:,1),LVV08upper(:,2));
% x = [LVV08lower(:,1)', fliplr(LVV08upper(:,1)')];
% inBetween = [LVV08lower(:,2)', fliplr(LVV08upper(:,2)')];
% fill(x, inBetween, [1 1 0]);
% plot(RW04lower(:,1),RW04lower(:,2));
% plot(RW04upper(:,1),RW04upper(:,2));
% x = [RW04lower(:,1)', fliplr(RW04upper(:,1)')];
% inBetween = [RW04lower(:,2)', fliplr(RW04upper(:,2)')];
% fill(x, inBetween, [0 1 0]);
% ax=gca;
% ax.YScale='log';
% grid on;
% ax.Layer='bottom';
% text(0.1,1e15,'Robertson et al.','FontSize',14);
% text(0.8,5e13,'Hwang et al., Lobashev et al.','FontSize',14);
% %text(1.6,1e12,'Lobashev et al.','FontSize',14);
% text(1,5e11,'KRN1 Twins','FontSize',14,'FontWeight','bold');
% text(0.6,3e10,'KATRIN Sensitivity limit (Bkg rate 130 mcps)','FontSize',14,'FontWeight','bold');
% text(0.1,1e9,'Kaboth et al.: KATRIN sensitivity limit (design Bkg)','FontSize',14);
% text(1.3,7e6,'Fässler et al.','FontSize',14);
% text(1,5e3,'Lazauskas et al.','FontSize',14);
% text(1,10,sprintf('Ringwald & Wong \n (extrapolated)'),'FontSize',14);
% xlabel('m_{\nu}');
% ylabel('\eta (90% C.L.)');
% xlim([0 2]);
% PrettyFigureFormat;
% hold off;
% 
% A=ref_RelicNuBkg_DesignReport('ToggleES','ON','eta_i',2e9);
% B=ref_RelicNuBkg_DesignReport('ToggleES','OFF','eta_i',2e9);
% A.ComputeTBDDS;B.ComputeTBDDS;A.ComputeTBDIS;B.ComputeTBDIS;
% fig2=figure('Renderer','painters');
% set(fig2, 'Units', 'normalized', 'Position', [0.001, 0.001,0.45, 0.45]);
% semilogy(A.qU-A.Q,A.TBDIS_R./(A.TBDIS-A.TBDIS_R),'LineWidth',2);
% hold on;
% semilogy(B.qU-B.Q,B.TBDIS_R./(B.TBDIS-B.TBDIS_R),'LineWidth',2);
% xlabel('E-E_0');
% ylabel('n_{C\nuB}/n_\beta (integral)');
% legend('Full C\nuB int spec','Ground state only','box','off','location','northwest');
% ylim([5e-7 1e-2]);
% xlim([-50 inf]);
% x1=[0.55 0.775];
% y1=[0.6 0.8];
% str1={'Ground state:','~1e-2 at sensitivity limit,','barely detectable'};
% a=annotation('textarrow',x1,y1,'String',str1);
% a.FontSize=16;
% x2=[0.45 0.2];
% y2=[0.25 0.24];
% str2={'Excited states:','~1e-6, undetectable'};
% b=annotation('textarrow',x2,y2,'String',str2);
% b.FontSize=16;
% PrettyFigureFormat;
% hold off;
% 
% fig3=figure('Renderer','painters');
% set(fig3, 'Units', 'normalized', 'Position', [0.001, 0.001,0.45, 0.45]);
% semilogy(A.Te-A.Q,A.TBDDS_R,'LineWidth',2);
% hold on;
% plot(B.Te-B.Q,B.TBDDS_R,'LineWidth',2);
% xlabel('E-E_0');
% ylabel('Rate per 0.1 eV per second');
% xlim([-30 inf]);
% ylim([1e-6 2e-4]);
% legend('Full C\nuB diff spec','Gaussian fit of ground state','box','off','location','northwest');
% PrettyFigureFormat;
% hold off;
% 
% fig4=figure('Renderer','painters');
% set(fig4, 'Units', 'normalized', 'Position', [0.001, 0.001,0.45, 0.5]);
% A=ref_RelicNuBkg_KNM1('TTFSD','OFF','HTFSD','OFF','DTFSD','OFF','mnuSq_i',2);
% B=ref_RelicNuBkg_KNM1('mnuSq_i',2);
% a=semilogy(A.Te-A.Q,A.TBDDS,'LineWidth',2);
% hold on;
% b=semilogy(A.Te-A.Q,A.TBDDS_R,'LineWidth',2);
% c=semilogy(B.Te-B.Q,B.TBDDS,'LineWidth',2);
% d=semilogy(B.Te-B.Q,B.TBDDS_R,'LineWidth',2);
% ylabel('Rate per Energy Bin');
% xlabel('Energy - E_{0} (eV)');
% legend([a b c d],'\beta decay, \sigma_{GS}=E_{GS}=0','C\nuB, \sigma_{GS}=E_{GS}=0','\beta decay, full model','C\nuB, full model');
% legend boxoff;
% xlim([-6 4]);
% ylim([1e-10 1e14]);
% x1=[0.705 0.705];
% y1=[0.6 0.15];
% a=annotation('line',x1,y1);
% a.LineStyle='--';
% a.LineWidth=2;
% a.Color=[0.5 0.5 0.5];
% x2=[0.571 0.571];
% y2=[0.6 0.35];
% b=annotation('line',x2,y2);
% b.LineStyle='--';
% b.LineWidth=2;
% b.Color=[0.5 0.5 0.5];
% x3=[0.62 0.705];
% y3=[0.3 0.3];
% c=annotation('textarrow',x3,y3,'String','2m_\nu');
% c.FontSize=16;
% x4=[0.57 0.483];
% y4=[0.3 0.3];
% d=annotation('arrow',x4,y4);
% x5=[0.665 0.705];
% y5=[0.55 0.55];
% e=annotation('textarrow',x5,y5,'String','E_{GS}');
% e.FontSize=16;
% x6=[0.615 0.571];
% y6=[0.55 0.55];
% f=annotation('arrow',x6,y6);
% PrettyFigureFormat;
% hold off;
% 
% relic_global('range',30,'annotations','ON','saveplot','ON');
% 
% PlotBestFit('DataType','Twin','saveplot','ON');
% PlotBestFit('DataType','Twin','Nfit',1000,'saveplot','ON');
% PlotBestFit('DataType','Real','saveplot','ON');
% 
RelicSystematics('ON','Twin');
RelicSystematics('ON','real');

fig5=figure('Renderer','painters');
set(fig5, 'Units', 'normalized', 'Position', [0.001, 0.001,0.45, 0.45]);
load('./RelicNuBkg/UpperLimits/EtaFit_mNu0_4_SystON_DataTypeTwinSinglemnuSq_TwinBias_mnuSq0_E0 Norm Bkg eta.mat');
[a,b] = boundedline(sqrt(mNu),etaFit,eta-etaFit);
ylim([0 3.4e11]);
xlim([0 1]);
xlabel('m_{\nu}');
ylabel('\eta');
legend([a b],'\eta best fit','90% C.L.','box','off','location','northwest');
PrettyFigureFormat;

fig6=figure('Renderer','painters');
set(fig6, 'Units', 'normalized', 'Position', [0.001, 0.001,0.45, 0.6]);
load('./RelicNuBkg/Chi2Scans/RelicChi2Scan_Twin_BiasmnuSq0_SystOFF_range40_KNM1_2D.mat');
[~,t]=contour(mnuScanPoints,etaScanPoints,Chi2',[0 4.61]);
t.LineWidth=2;
t.ShowText='on';
xlabel('m_\nu');
ylabel('\eta');
xlim([-inf 2.1]);
PrettyFigureFormat;

fig7=figure('Renderer','painters');
set(fig7, 'Units', 'normalized', 'Position', [0.001, 0.001,0.45, 0.45]);
load('./RelicNuBkg/UpperLimits/EtaFit_mNu0_1_SystON_DataTypeRealSinglemnuSq_TwinBias_mnuSq0_E0 Norm Bkg etaDeltaChi2_1.mat');
eta90=eta;
etaFit90=etaFit;
load('./RelicNuBkg/UpperLimits/EtaFit_mNu0_1_SystON_DataTypeRealSinglemnuSq_TwinBias_mnuSq0_E0 Norm Bkg etaDeltaChi2_4.mat');
eta95=eta;
etaFit95=etaFit;
load('./RelicNuBkg/UpperLimits/EtaFit_mNu0_1_SystON_DataTypeRealSinglemnuSq_TwinBias_mnuSq0_E0 Norm Bkg etaDeltaChi2_9.mat');
hold on;
[~,b] = boundedline(sqrt(mNu),etaFit90,eta90,'cmap',[0 0.75 0.75]);
[~,d] = boundedline(sqrt(mNu),etaFit95,eta95,'cmap',[0 0.5 0.5],'alpha');
[~,f] = boundedline(sqrt(mNu),etaFit,eta,'cmap',[0 0.25 0.25],'alpha');
text(0.1,3.3e11,'1\sigma C.L.','FontSize',14);
text(0.4,5e11,'2\sigma C.L.','FontSize',14);
text(0.7,6.5e11,'3\sigma C.L.','FontSize',14);
ylim([0 inf]);
xlabel('m_{\nu}');
ylabel('\eta');
PrettyFigureFormat;
hold off;

fig8=figure('Renderer','painters');
set(fig8, 'Units', 'normalized', 'Position', [0.001, 0.001,0.45, 0.6]);
load('./RelicNuBkg/Chi2Scans/RelicChi2Scan_Twin_BiasmnuSq0_SystON_range40_KNM1_2D_Real.mat');
hold on;
[~,t]=contour(mnuScanPoints,etaScanPoints,(Chi2-GlobalChi2Min).',[0 2.3]);
t.LineWidth = 2;
[~,u]=contour(mnuScanPoints,etaScanPoints,(Chi2-GlobalChi2Min).',[0 6.18]);
u.LineWidth = 2;
[~,v]=contour(mnuScanPoints,etaScanPoints,(Chi2-GlobalChi2Min).',[0 11.83]);
v.LineWidth = 2;
ylabel('\eta','FontSize',12);
xlabel('m_{\nu}^{2} (eV^{2})','FontSize',12);
zlabel('\Delta\chi^2','FontSize',12);
title('\Delta\chi^2');
text(0,2.5e11,'1\sigma C.L.','FontSize',14);
text(-0.5,4e11,'2\sigma C.L.','FontSize',14);
text(-0.25,6e11,'3\sigma C.L.','FontSize',14);
xlim([-1,1]);
ylim([0,inf]);
PrettyFigureFormat;
hold off;

if strcmp(saveplot,'ON')
    SaveDir = [getenv('SamakPath'),sprintf('RelicNuBkg/Plots/FinalPlots/')];
    MakeDir(SaveDir);
    SaveName1='SensitivityLimitComparison.pdf';
    SaveName2='ExcitedStates_SoverB.pdf';
    SaveName3='CnuB_DiffSpec.pdf';
    SaveName4='FSDeffects.pdf';
    SaveName5='TwinRaster.pdf';
    SaveName6='Twin2D.pdf';
    SaveName7='DataRaster.pdf';
    SaveName8='Data2D.pdf';
    export_fig(fig1,[SaveDir,SaveName1]);
    export_fig(fig2,[SaveDir,SaveName2]);
    export_fig(fig3,[SaveDir,SaveName3]);
    export_fig(fig4,[SaveDir,SaveName4]);
    export_fig(fig5,[SaveDir,SaveName5]);
    export_fig(fig6,[SaveDir,SaveName6]);
    export_fig(fig7,[SaveDir,SaveName7]);
    export_fig(fig8,[SaveDir,SaveName8]);
end