% investigate impact of different grid types on contour 
nGridSteps = 25;
mNu4SqTestGrid = [1,2,3];
Mode = 'Compute';
%% configure RunAnalysis object
chi2 = 'chi2Stat';
DataType = 'Twin';
range = 40;
InterpMode = 'spline';
if strcmp(chi2,'chi2Stat')
    NonPoissonScaleFactor = 1;
elseif  strcmp(chi2,'chi2CMShape')
    NonPoissonScaleFactor = 1.112;
end
RunAnaArg = {'RunList','KNM2_Prompt',...
    'DataType',DataType,...
    'fixPar','E0 Norm Bkg',...%free par
    'SysBudget',40,...
    'fitter','minuit',...
    'minuitOpt','min;migrad',...
    'RadiativeFlag','ON',...
    'FSDFlag','KNM2_0p1eV',...
    'ELossFlag','KatrinT2A20',...
    'AnaFlag','StackPixel',...
    'chi2',chi2,...
    'NonPoissonScaleFactor',NonPoissonScaleFactor,...
    'FSD_Sigma',sqrt(0.0124+0.0025),...
    'TwinBias_FSDSigma',sqrt(0.0124+0.0025),...
    'TwinBias_Q',18573.7,...
    'PullFlag',99,...;%99 = no pull
    'BKG_PtSlope',3*1e-06,...
    'TwinBias_BKG_PtSlope',3*1e-06,...
    'DopplerEffectFlag','FSD'};
A = MultiRunAnalysis(RunAnaArg{:});
%% configure Sterile analysis object
SterileArg = {'RunAnaObj',A,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',nGridSteps,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',range};
S = SterileAnalysis(SterileArg{:});
%%

switch Mode
    case 'Compute'
        for i=1:numel(mNu4SqTestGrid)
            S.GridSearch('mNu4SqTestGrid',mNu4SqTestGrid(i),'ExtmNu4Sq','ON');
        end
        S.GridSearch('mNu4SqTestGrid','OFF','ExtmNu4Sq','ON');
    case 'Display'
        Color = {'Orange','FireBrick','LimeGreen','ForestGreen'};
        LineStyle = {'-.',':','--','-','-.',':','--','-'};
        pHandle = cell(numel(mNu4SqTestGrid)+1,1);
        S.LoadGridFile('mNu4SqTestGrid','OFF','ExtmNu4Sq','ON');
        mNu50 = S.mNu4Sq(:,1);
        S.Interp1Grid('Maxm4Sq',38.2^2)
        pHandle{1} = S.ContourPlot('HoldOn','OFF');
        for i=1:numel(mNu4SqTestGrid)
            S.LoadGridFile('mNu4SqTestGrid',mNu4SqTestGrid(i),'ExtmNu4Sq','ON');
             mNu25 =S.mNu4Sq(:,1);
            S.Interp1Grid('Maxm4Sq',38.2^2)
            pHandle{i+1} = S.ContourPlot('HoldOn','ON','Color',rgb(Color{i}),'LineStyle',LineStyle{i});
        end
end
