% Test SterileAnalysis class
% Lisa, May2020
% plot with neutrino mass as
% nuissance parameter free
% nuissance parameter + pull
% fixed parameter
%% settings for runanalysis
DataType = 'Real';
freePar = 'E0 Norm Bkg';
%%
RunAnaArg = {'RunList','KNM1',...
    'fixPar',freePar,...
    'DataType',DataType,...
    'FSDFlag','SibilleFull',...
    'ELossFlag','KatrinT2',...
    'AnaFlag','StackPixel',...
    'chi2','chi2Stat',...
    'ROIFlag','Default',...
    'SynchrotronFlag','ON',...
    'AngularTFFlag','OFF',...
    'ISCSFlag','Edep',...
    'TwinBias_Q',18573.73,...
    'SysBudget',24,...
    'pullFlag',99,...
    'NonPoissonScaleFactor',1};

T = MultiRunAnalysis(RunAnaArg{:});
T.chi2 = 'chi2CMShape';
%% settings sterile class
SterileArg = {'RunAnaObj',T,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',50,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',40};

S = SterileAnalysis(SterileArg{:});

%% 2 load a chi2 map and find the best fit
S.LoadGridFile('CheckSmallerN','ON','CheckLargerN','ON'); % if CheckSmallerN also look for grid with more/less nGridSteps
%S.InterpMode = 'lin'; % waring: if contour is closed, spline interp sometimes sensitive to artefacts! Switch to "lin" in this case
S.Interp1Grid('RecomputeFlag','ON');% interpolate chi2 map -> nicer appearance of all plots. some

chi2_ref_i = S.chi2_ref;
chi2_ref = struct('PosM4NegSinT4', 21.6233);% minimal chi2 in negative parameter space
chi2_ref.NegM4PosSinT4 = 21.7718;
chi2_ref.NegM4NegSinT4 = 22.9289;

%%
CL = 95;
S.chi2_ref = chi2_ref_i;
pReg = S.ContourPlot('CL',CL,'HoldOn','OFF','Color',rgb('DodgerBlue'),'LineStyle','-','BestFit','OFF');
S.chi2_ref = chi2_ref.PosM4NegSinT4;
pPosNeg = S.ContourPlot('CL',CL,'HoldOn','ON','Color',rgb('Orange'),'LineStyle','--','BestFit','OFF');
S.chi2_ref = chi2_ref.NegM4PosSinT4;
pNegPos = S.ContourPlot('CL',CL,'HoldOn','ON','Color',rgb('IndianRed'),'LineStyle',':','BestFit','OFF');
S.chi2_ref = chi2_ref.NegM4NegSinT4;
pNegNeg = S.ContourPlot('CL',CL,'HoldOn','ON','Color',rgb('LimeGreen'),'LineStyle','-.','BestFit','OFF');
%%
 leg = legend([pReg,pPosNeg,pNegPos,pNegNeg],...
         sprintf('\\chi^2_{min} = %.2f (pos. {\\itm}^2_4, pos. |{\\itU}_{e4}|^2)',chi2_ref_i),...
         sprintf('\\chi^2_{min} = %.2f (pos. {\\itm}^2_4, neg.|{\\itU}_{e4}|^2)',chi2_ref.PosM4NegSinT4),...
         sprintf('\\chi^2_{min} = %.2f (neg. {\\itm}^2_4, pos. |{\\itU}_{e4}|^2)',chi2_ref.NegM4PosSinT4),...
         sprintf('\\chi^2_{min} = %.2f (neg. {\\itm}^2_4, neg. |{\\itU}_{e4}|^2)',chi2_ref.NegM4NegSinT4));
xlim([8e-03,0.5]);
ylim([1 2e3]);
%% save
plotdir = sprintf('%sSterileAnalysis/plots/%s/%s/', getenv('SamakPath'),'Knm1',DataType);
MakeDir(plotdir);
plotname = sprintf('%sNegParSpaceContour_%s_%.0feV_%s',plotdir,DataType,S.range,strrep(freePar,' ',''));
print(gcf,[plotname,'.png'],'-dpng','-r300');
export_fig(gcf,[plotname,'.pdf']);
print(gcf,[plotname,'.png'],'-dpng','-r300');
fprintf('save plot to %s \n',plotname);

