addpath(genpath('../../../Samak2.0'));
close all

% Build FSD Covariance Matrix with a given TD
A = ref_FTMTD();

% Define your CM Class with your number of trials, choose SysEffect,...
myEffects = struct(...
    'RF_EL','ON',...  % Response Function(RF) EnergyLoss
    'RF_BF','ON',...  % RF B-Fields
    'RF_RX','ON'...  % RF Column Density, Cross Section
    );
C = CovarianceMatrix('StudyObject',A,...
    'nTrials',1000,...
    'RunFlag','OFF', 'nRuns',1,...
    'SysEffect',myEffects,...
    'MACE_Ba_T_RelErr',1e-2,...
    'MACE_Bmax_T_RelErr',1e-2,...
    'WGTS_B_T_RelErr',1e-2,...
    'WGTS_CD_MolPerCm2_RelErr',0.1,...
    'RecomputeFlag','OFF');
C.ComputeCM_RF;
%C.ComputeCM;

% Plot
C.PlotCM

% Decompose
C.DecomposeCM
