addpath(genpath('../../../Samak2.0'));
close all

% Build FSD Covariance Matrix with a given TD
A = ref_FTMTD();

% Define your CM Class with your number of trials, choose SysEffect,...
myEffects = struct(...
    'TASR','ON');
C = CovarianceMatrix('StudyObject',A,...
    'nTrials',1000,...
    'RunFlag','OFF', 'nRuns',1,...
    'SysEffect',myEffects,...
    'WGTS_TASR_RelErr',1e-2,...
    'RecomputeFlag','ON');
C.ComputeCM_TASR;
%C.ComputeCM;

% Plot
C.PlotCM

% Decompose
C.DecomposeCM
