% extend grid for those randMC that yielded best fit on grid boundary

% grid search on randomized twins
% ksn2 calculate chi2 grid search
randMC = 1:1e3;
NrandMC = 1e3;
Twin_sin2T4 = 0;
Twin_mNu4Sq = 0;
chi2 = 'chi2CMShape';
DataType = 'Twin';
freePar = 'E0 Norm Bkg';
nGridSteps = 25;
range = 40;

%% get summary file
savedir = [getenv('SamakPath'),'ksn2ana/ksn2_WilksTheorem/results/'];
if Twin_sin2T4==0 && Twin_mNu4Sq==0
    savefile = sprintf('%sksn2_WilksTheorem_NullHypothesis_%.0fsamples.mat',savedir,NrandMC);
else
    savefile = sprintf('%sksn2_WilksTheorem_mNu4Sq-%.1feV2_sin2T4-%.3g_%.0fsamples.mat',savedir,Twin_mNu4Sq,Twin_sin2T4,NrandMC);
end

if exist(savefile,'file') 
    fprintf('load file %s \n',savefile);
    d = importdata(savefile);
else
     fprintf('file missing %s \n',savefile);
    return
end

% find fits on grid boundary: sin2t4==0.5
Idx= find(d.sin2T4_bf==0.5);

%% configure RunAnalysis object
if strcmp(chi2,'chi2Stat')
    NonPoissonScaleFactor = 1;
elseif  strcmp(chi2,'chi2CMShape')
    NonPoissonScaleFactor = 1.112;
end
RunAnaArg = {'RunList','KNM2_Prompt',...
    'DataType',DataType,...
    'fixPar',freePar,...%free par
    'SysBudget',40,...
    'fitter','minuit',...
    'minuitOpt','min;migrad',...
    'RadiativeFlag','ON',...
    'FSDFlag','KNM2_0p5eV',...
    'ELossFlag','KatrinT2A20',...
    'AnaFlag','StackPixel',...
    'chi2',chi2,...
    'NonPoissonScaleFactor',NonPoissonScaleFactor,...
    'FSD_Sigma',sqrt(0.0124+0.0025),...
    'TwinBias_FSDSigma',sqrt(0.0124+0.0025),...
    'TwinBias_Q',18573.7,...
    'PullFlag',99,...;%99 = no pull
    'BKG_PtSlope',3*1e-06,...
    'TwinBias_BKG_PtSlope',3*1e-06,...
    'DopplerEffectFlag','FSD'};
A = MultiRunAnalysis(RunAnaArg{:});
%% configure Sterile analysis object
SterileArg = {... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',nGridSteps,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'range',range,...
    'RandMC','OFF',...
    'Twin_mNu4Sq',Twin_mNu4Sq,...
    'Twin_sin2T4',Twin_sin2T4};
%%
for i=1:numel(Idx)
    A = MultiRunAnalysis(RunAnaArg{:});
    S = SterileAnalysis('RunAnaObj',A,SterileArg{:});
    S.RandMC= randMC(Idx(i));
    %%
    df = importdata(S.GridFilename('mNu4SqTestGrid',2,'ExtmNu4Sq','ON'));
    S.RandMC_TBDIS = df.TBDIS_mc;
    S.GridSearch('mNu4SqTestGrid',6,'ExtmNu4Sq','ON');
end