% KNM1 Final fit Results
% Uniform Fit
% Golden Run List
% Golden Pixel List
%% settings
RunList               = 'KNM1';
exclDataStart         = 14; % 40eV range = 27 subruns
%% Init Model Object and covariance matrix object
Real = MultiRunAnalysis('RunList',RunList,...
    'chi2','chi2Stat','DataType','Real',...
    'exclDataStart',exclDataStart,...
    'fixPar','mNu E0 Norm Bkg',...
    'RadiativeFlag','ON',...
    'NonPoissonScaleFactor',1.064,...
    'minuitOpt','min ; minos',...
    'FSDFlag','Sibille',...
    'ELossFlag','KatrinT2',...
    'SysBudget',22);
%% Get Covariance Matrix
Real.chi2='chi2CMShape';%'; % shape-only mode
Real.ComputeCM;
%% Fit
Real.Fit('CATS','OFF');
%% Display fit and save plot
Real.PlotFit('LabelFlag','FinalKNM1',...
    'saveplot','pdf',...
    'ErrorBarScaling',1,...
    'YLimRes',[-2.2,2.9],...
    'Colors','RGB',...
    'DisplayStyle','PRL',...
    'FitResultsFlag','OFF',...
    'qUDisp','Rel');
