
% KNM1 Final fit Results
% Uniform Fit
% Golden Run List
% Golden Pixel List
%  Twin data with stat fluctuations
% Last Updated: 10/09/2019
%
%% settings
RunList               = 'KNM1';
exclDataStart         = 14; % 27 subruns
RecomputeFlag         = 'OFF';

%% Init Model Object and covariance matrix object
Twin = MultiRunAnalysis('RunList',RunList,...
    'chi2','chi2Stat','DataType','Twin',...
    'exclDataStart',exclDataStart,...
    'fixPar','5 6 7 8 9 10 11',...
    'RadiativeFlag','ON',...
    'NonPoissonScaleFactor',1.064,...
    'minuitOpt','min ; minos',...
    'FSDFlag','Sibille0p5eV',...%'SAENZ',...%Sibille0p5eV',...%'Sibille',...
    'ELossFlag','KatrinT2',...
    'SysBudget',22);
Twin.chi2 = 'chi2CMShape';
Twin.ComputeCM;
Twin.FitTwin('nSamples',1)
%% plot & save as pdf & png
Twin.PlotFit('LabelFlag','FinalKNM1','saveplot','pdf','ErrorBarScaling',50,'YLimRes',[-2.2,2.9],'Colors',...
    'RGB','DisplayStyle','PRL','FitResultsFlag','OFF','qUDisp','Rel');
Twin.PlotFit('LabelFlag','FinalKNM1','saveplot','pdf','ErrorBarScaling',1,'YLimRes',[-2.2,2.9],'Colors',...
    'RGB','DisplayStyle','PRL','FitResultsFlag','OFF','qUDisp','Rel');

Twin.PlotFit('LabelFlag','FinalKNM1','saveplot','png','ErrorBarScaling',50,'YLimRes',[-2.2,2.9],'Colors',...
    'RGB','DisplayStyle','PRL','FitResultsFlag','OFF','qUDisp','Rel');
Twin.PlotFit('LabelFlag','FinalKNM1','saveplot','png','ErrorBarScaling',1,'YLimRes',[-2.2,2.9],'Colors',...
    'RGB','DisplayStyle','PRL','FitResultsFlag','OFF','qUDisp','Rel');