function RunStruct = SimFakeRun(varargin)
% 
p = inputParser;
p.addParameter('RunNr',1000001,@(x)(isfloat(x) && x>0));
p.addParameter('TimeSec',7200,@(x)(isfloat(x) && x>0));
p.addParameter('RunTimeStart',datetime([2019 03 1 12 00 00]));

% sub-Runs Retarding Voltages
p.addParameter('TD','MTDcreator_E018575.0_30eV_B35_Ba6.0_RedF0.7_NuMF0.60_BkgF0.15_B350');
p.addParameter('qUDeltaMinus',-0.1,@(x)(isfloat(x) && x>0));
p.addParameter('qUDeltaPlus',+0.1,@(x)(isfloat(x) && x>0));

% Column Density
p.addParameter('WGTS_CD_MolPerCm2_i',5e+17,@(x)(isfloat(x) && x>0));
p.addParameter('WGTS_CD_MolPerCm2_b',0,@(x)(isfloat(x) && x>0));
p.addParameter('WGTS_CD_MolPerCm2_s',5e+17/500,@(x)(isfloat(x) && x>0));

% DT
p.addParameter('WGTS_MolFrac_DT_i',0.05,@(x)(isfloat(x) && x>0));
p.addParameter('WGTS_MolFrac_DT_b',0.,@(x)(isfloat(x) && x>0));
p.addParameter('WGTS_MolFrac_DT_s',0.05/200,@(x)(isfloat(x) && x>0));
% TT
p.addParameter('WGTS_MolFrac_TT_i',0.9,@(x)(isfloat(x) && x>0));
p.addParameter('WGTS_MolFrac_TT_b',0.,@(x)(isfloat(x) && x>0));
p.addParameter('WGTS_MolFrac_TT_s',0.9/200,@(x)(isfloat(x) && x>0));
% HT
p.addParameter('WGTS_MolFrac_HT_i',0.05,@(x)(isfloat(x) && x>0));
p.addParameter('WGTS_MolFrac_HT_b',0.,@(x)(isfloat(x) && x>0));
p.addParameter('WGTS_MolFrac_HT_s',0.05/200,@(x)(isfloat(x) && x>0));

% Background
p.addParameter('BKG_RateAllFPDSec',0.430,@(x)(isfloat(x) && x>0));

% Produce FakeRun File
p.addParameter('SimFakeRunPath','.');
p.addParameter('SimFakeRunSave','ON',@(x)ismember(x,{'ON','OFF'}));
p.addParameter('SimTDRunPath','../../simulation/katrinsetup/TD_DataBank/');

p.parse(varargin{:});
RunNr                       = p.Results.RunNr;
TimeSec                     = p.Results.TimeSec;
RunTimeStart                = p.Results.RunTimeStart;
TD                          = p.Results.TD;
qUDeltaMinus                = p.Results.qUDeltaMinus;
qUDeltaPlus                 = p.Results.qUDeltaPlus;
WGTS_CD_MolPerCm2_i         = p.Results.WGTS_CD_MolPerCm2_i;
WGTS_CD_MolPerCm2_b         = p.Results.WGTS_CD_MolPerCm2_b;
WGTS_CD_MolPerCm2_s         = p.Results.WGTS_CD_MolPerCm2_s;
WGTS_MolFrac_DT_i           = p.Results.WGTS_MolFrac_DT_i;
WGTS_MolFrac_DT_b           = p.Results.WGTS_MolFrac_DT_b;
WGTS_MolFrac_DT_s           = p.Results.WGTS_MolFrac_DT_s;
WGTS_MolFrac_TT_i           = p.Results.WGTS_MolFrac_TT_i;
WGTS_MolFrac_TT_b           = p.Results.WGTS_MolFrac_TT_b;
WGTS_MolFrac_TT_s           = p.Results.WGTS_MolFrac_TT_s;
WGTS_MolFrac_HT_i           = p.Results.WGTS_MolFrac_HT_i;
WGTS_MolFrac_HT_b           = p.Results.WGTS_MolFrac_HT_b;
WGTS_MolFrac_HT_s           = p.Results.WGTS_MolFrac_HT_s;
BKG_RateAllFPDSec           = p.Results.BKG_RateAllFPDSec;
SimFakeRunPath              = p.Results.SimFakeRunPath;
SimFakeRunSave              = p.Results.SimFakeRunSave;
SimTDRunPath                = p.Results.SimTDRunPath;

% TD
TDfile            = load([TD '.mat']); nqU=numel(TDfile.qU);
qU                = TDfile.qU + qUDeltaMinus  + (qUDeltaPlus-qUDeltaMinus).*rand(nqU,1);
qUfrac            = TDfile.qUfrac;

% Initial Object
RefFile = 'RunAnalysis';
switch RefFile
    case 'Sensitivity'
        SimFakeObj_i = ref_sensitivity(...
            'TD',TD,...
            'TimeSec',TimeSec ,...
            'WGTS_CD_MolPerCm2',WGTS_CD_MolPerCm2_i,...
            'WGTS_MolFrac_TT',WGTS_MolFrac_TT_i ,...
            'WGTS_MolFrac_HT',WGTS_MolFrac_HT_i ,...
            'WGTS_MolFrac_DT',WGTS_MolFrac_DT_i ,...
            'BKG_RateAllFPDSec',BKG_RateAllFPDSec);
    case 'RunAnalysis'
        nTeBinningFactor = 50;
        WGTS_B_T         = 2.52;
        MACE_Bmax_T      = 4.2;
        MACE_Ba_T        = 6e-4;
        ISCS             = 'Theory'; Mode = 'Read';
        mnuSq_i          = 0;
        Q_i              = 18573.7;
        DTFSD            = 'HTFSD';
        HTFSD            = 'SAENZ';
        TTFSD            = 'SAENZ';
        ELossFlag        = 'Abdurashitov';
        DopplerEffectFlag= 'OFF';
        FPD_MeanEff      = 0.95;
        FPD_ROIlow       = 14;
        FPD_ROIEff       = 'OFF';
        FPD_PileUpEff    = 'OFF';
        BKG_Flag         = 'ON';
        BKG_Type         = 'FLAT';
        FPD_Segmentation = 'OFF';
        KTFFlag          = 'Compute';
        recomputeRF      = 'OFF';
        UseParallelRF    = 'ON';
        FPD_Pixel        = 1;
        FPD_Ring         = 1;

        opt_calc = {...
            'nTeBinningFactor',nTeBinningFactor};
        
        opt_katrin = {...
            'Mode',Mode,...
            'TD',TD,...
            'TimeSec',TimeSec,...
            'mnuSq_i',mnuSq_i,...
            'Q_i',Q_i};

        opt_wgts = {...
            'WGTS_MolFrac_TT',WGTS_MolFrac_TT_i,...
            'WGTS_MolFrac_TT_SubRun',repmat(WGTS_MolFrac_TT_i,1,nqU),...
            'WGTS_MolFrac_DT',WGTS_MolFrac_DT_i,...
            'WGTS_MolFrac_DT_SubRun',repmat(WGTS_MolFrac_DT_i,1,nqU),...
            'WGTS_MolFrac_HT',WGTS_MolFrac_HT_i,...
            'WGTS_MolFrac_HT_SubRun',repmat(WGTS_MolFrac_HT_i,1,nqU),...
            'WGTS_MolFracRelErr_TT',0,...
            'WGTS_MolFracRelErr_DT',0,...
            'WGTS_MolFracRelErr_HT',0,...
            'WGTS_DTHTr',1,...
            'WGTS_FTR_cm',4.1,...
            'WGTS_CD_MolPerCm2',WGTS_CD_MolPerCm2_i,...
            'WGTS_CD_MolPerCm2_SubRun',repmat(WGTS_CD_MolPerCm2_i,1,nqU),...
            'WGTS_B_T',WGTS_B_T,...
            'WGTS_Temp',30,...
            'ISCS',ISCS,...
            'ELossFlag',ELossFlag,...
            'recomputeRF',recomputeRF,...
            'UseParallelRF',UseParallelRF};
        
        opt_mace = {...
            'MACE_Bmax_T',MACE_Bmax_T,...
            'MACE_Ba_T',MACE_Ba_T};
        
        opt_wgtsmace = {...
            'KTFFlag',KTFFlag};
        
        opt_fpd = {...
            'FPD_Segmentation',FPD_Segmentation,...
            'FPD_Pixel',FPD_Pixel,...
            'FPD_Ring',FPD_Ring,...
            'FPD_MeanEff',FPD_MeanEff,...
            'FPD_ROIEff',FPD_ROIEff,...
            'FPD_ROIlow',FPD_ROIlow,...
            'FPD_PileUpEff',FPD_PileUpEff};
        
        opt_bkg = {...
            'BKG_Flag',BKG_Flag,...
            'BKG_Type',BKG_Type,...
            'BKG_RateAllFPDSec',BKG_RateAllFPDSec};
        
        opt_fsd= {...
            'TTFSD',TTFSD,...
            'DTFSD',DTFSD,...
            'HTFSD',HTFSD};
        
        opt_doppler = {'DopplerEffectFlag',DopplerEffectFlag};
        
        opt_integration = {'IStype','SIMPFAST'};
        
        opt_corr= {...
            'RadiativeFlag','ON'};
        
        % Tritium spectrum definition
        SimFakeObj_i  = TBD(...
            opt_corr{:},...
            opt_calc{:},...
            opt_katrin{:},...
            opt_wgts{:},...
            opt_mace{:},...
            opt_fpd{:},...
            opt_wgtsmace{:},...
            opt_fsd{:},...
            opt_bkg{:},...
            opt_doppler{:},...
            opt_integration{:});
        
end

SimFakeObj_i.ComputeTBDDS; SimFakeObj_i.ComputeTBDIS;

% SC
WGTS_CD_MolPerCm2_SubRun = GenSCRandomBias(WGTS_CD_MolPerCm2_i,WGTS_CD_MolPerCm2_b,WGTS_CD_MolPerCm2_s,nqU);
WGTS_MolFrac_DT_SubRun   = GenSCRandomBias(WGTS_MolFrac_DT_i,WGTS_MolFrac_DT_b,WGTS_MolFrac_DT_s,nqU);
WGTS_MolFrac_TT_SubRun   = GenSCRandomBias(WGTS_MolFrac_TT_i,WGTS_MolFrac_TT_b,WGTS_MolFrac_TT_s,nqU);
WGTS_MolFrac_HT_SubRun   = GenSCRandomBias(WGTS_MolFrac_HT_i,WGTS_MolFrac_HT_b,WGTS_MolFrac_HT_s,nqU);


% Builiod TD Structure
TDStruct.RunTime            = TimeSec;
TDStruct.TD                 = TD;
TDStruct.qU                 = qU;
TDStruct.qUfrac             = qUfrac;

% Build Fake Data Structure: General
RunStruct.TD                 = TD;
RunStruct.qU                 = qU;
RunStruct.qUfrac             = qUfrac;
% Build Fake Data Structure: Time
RunStruct.RunNr              = RunNr;
RunStruct.TimeSec            = TimeSec;
RunStruct.RunTimeStart       = RunTimeStart;
% Build Fake Data Structure: SC
RunStruct.WGTS_CD_MolPerCm2_SubRun  = WGTS_CD_MolPerCm2_SubRun;
RunStruct.WGTS_CD_MolPerCm2         = mean(WGTS_CD_MolPerCm2_SubRun);
RunStruct.WGTS_MolFrac_DT_SubRun    = WGTS_MolFrac_DT_SubRun;
RunStruct.WGTS_MolFrac_DT           = mean(WGTS_MolFrac_DT_SubRun);
RunStruct.WGTS_MolFrac_TT_SubRun    = WGTS_MolFrac_TT_SubRun;
RunStruct.WGTS_MolFrac_TT           = mean(WGTS_MolFrac_TT_SubRun);
RunStruct.WGTS_MolFrac_HT_SubRun    = WGTS_MolFrac_HT_SubRun;
RunStruct.WGTS_MolFrac_HT           = mean(WGTS_MolFrac_HT_SubRun);

% Build Fake Data Structure: TBDIS
switch RefFile
    case 'Sensitivity'
        SimFakeObj = ref_sensitivity(...
    'TD',RunStruct.TD,...
    'TimeSec',RunStruct.TimeSec ,...
    'WGTS_CD_MolPerCm2',RunStruct.WGTS_CD_MolPerCm2,...
    'WGTS_MolFrac_TT',RunStruct.WGTS_MolFrac_TT ,...
    'WGTS_MolFrac_HT',RunStruct.WGTS_MolFrac_HT ,...
    'WGTS_MolFrac_DT',RunStruct.WGTS_MolFrac_DT ,...
    'BKG_RateAllFPDSec',BKG_RateAllFPDSec);
    case 'RunAnalysis'
        SimFakeObj  = TBD(...
            opt_corr{:},...
            opt_calc{:},...
            opt_katrin{:},...
            opt_wgts{:},...
            opt_mace{:},...
            opt_fpd{:},...
            opt_wgtsmace{:},...
            opt_fsd{:},...
            opt_bkg{:},...
            opt_doppler{:},...
            opt_integration{:},...
            'TD',RunStruct.TD,...
            'TimeSec',RunStruct.TimeSec ,...
            'WGTS_CD_MolPerCm2',RunStruct.WGTS_CD_MolPerCm2,...
            'WGTS_MolFrac_TT',RunStruct.WGTS_MolFrac_TT ,...
            'WGTS_MolFrac_HT',RunStruct.WGTS_MolFrac_HT ,...
            'WGTS_MolFrac_DT',RunStruct.WGTS_MolFrac_DT ,...
            'BKG_RateAllFPDSec',BKG_RateAllFPDSec);
end

SimFakeObj.ComputeTBDDS; SimFakeObj.ComputeTBDIS;  SimFakeObj.AddStatFluctTBDIS;
RunStruct.TBDIS                     = SimFakeObj.TBDIS; 
RunStruct.TBDISE                    = sqrt(RunStruct.TBDIS);

% Write Fake Data Run Files
switch SimFakeRunSave
    case 'ON'
        %Fake Data
        save([SimFakeRunPath '/FakeRun' num2str(RunNr) '.mat'],'-struct','RunStruct');
        save([SimFakeRunPath '/FakeRunObject.mat'],'SimFakeObj_i');
        % TD
        TDStruct.TD                 = ['FakeRun' num2str(RunNr)];
        save([SimTDRunPath 'FakeRun' num2str(RunNr) '.mat'],'-struct','TDStruct');
end

end

function value = GenSCRandomBias(m,b,s,n)
value = repmat(m + b,1,n) + randn(1,n).*s;
end
