Mode = 'Real';
chi2 = 'chi2CMShape';
ELossFlag = 'KatrinT2';
FSDFlag = 'SibilleFull';
fixPar = '1 5 6 7 8 9 10 11';

ModelArg = {'chi2',chi2,...
    'minuitOpt','min  ; migrad ',...
    'RadiativeFlag','ON',...
    'FSDFlag',FSDFlag,...
    'ELossFlag',ELossFlag,...
    'fixPar',fixPar,...
    'DataType','Real'};


FT = MultiRunAnalysis(ModelArg{:},'RunList','FTpaper',...
                     'NonPoissonScaleFactor',1.0,...
                     'exclDataStart',13);  % 100 eV
                 
KNM1 = MultiRunAnalysis(ModelArg{:},'RunList','KNM1',...
                     'NonPoissonScaleFactor',1.064,...
                     'exclDataStart',14);  %40 eV               

                 