% KSNX KATRIN final sensitivity
% Lisa, May 2020
% 750 days
% 130 mcps background
% TDR like systematics
%% settings for RunAnalysis

nGridSteps = 50;
DataType   = 'Fake';
chi2       = 'chi2Stat';
freePar    = 'E0 Norm Bkg';

savedir = [getenv('SamakPath'),'ksnxana/ksnx_sensitivity/results/'];
MakeDir(savedir);
savename = sprintf('%sksnx_finalsensitivity_contour_%s_%s_nGridSteps%.0f.mat',savedir,chi2,strrep(freePar,' ',''),nGridSteps);

if exist(savename,'file')  & 1==2
else
    
    FakeInitFile = @ref_KSNX_KATRIN_Final2;
    RunAnaArg = {'RunNr',1,...
        'fixPar',freePar,...
        'DataType','Fake',...
        'FSDFlag','KNM2_0p5eV',...
        'ELossFlag','KatrinT2A20',...
        'AnaFlag','StackPixel',...
        'chi2','chi2Stat',...
        'SynchrotronFlag','ON',...
        'AngularTFFlag','ON',...
        'ISCSFlag','Edep',...
        'TwinBias_Q',18573.73,...
        'SysBudget',66,...
        'pullFlag',99,...
        'NonPoissonScaleFactor',1,...
        'FakeInitFile',FakeInitFile,...
        'PixList',1:136,...
        'DopplerEffectFlag','FSD'};
    
    T = RunAnalysis(RunAnaArg{:});
    T.chi2 = chi2;
    %% settings sterile class
    SterileArg = {'RunAnaObj',T,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
        'nGridSteps',nGridSteps,...
        'SmartGrid','OFF',...
        'RecomputeFlag','OFF',...
        'SysEffect','all',...
        'RandMC','OFF',...
        'range',40,...
        'LoadGridArg',{'ExtmNu4Sq','ON','mNu4SqTestGrid',2}};
    
    S = SterileAnalysis(SterileArg{:});
    %%   S.GridSearch(S.LoadGridArg{:});
    S.LoadGridFile(S.LoadGridArg{:});
    
    S.InterpMode = 'Mix';
    S.Interp1Grid('Maxm4Sq',36^2);
    S.ContourPlot;
    
    mNu4Sq = S.mNu4Sq_contour;
    sin2T4 = S.sin2T4_contour;
     save(savename,'mNu4Sq','sin2T4');
end