% KSNX KATRIN final sensitivity
% Lisa, May 2020
% 750 days
% 130 mcps background
% TDR like systematics
% neutrino mass sensitivity

FixmNuSq_all = (-1:0.1:1);

%% settings for runanalysis
nGridSteps = 40;
DataType   = 'Fake';
chi2       = 'chi2Stat';
freePar    = 'E0 Norm Bkg';

FakeInitFile = @ref_KSNX_KATRIN_Final2;

for i=1:numel(FixmNuSq_all)
    RunAnaArg = {'RunNr',1,...
        'fixPar',freePar,...
        'DataType','Fake',...
        'FSDFlag','KNM2_0p5eV',...
        'ELossFlag','KatrinT2A20',...
        'AnaFlag','StackPixel',...
        'chi2','chi2Stat',...
        'SynchrotronFlag','ON',...
        'AngularTFFlag','ON',...
        'ISCSFlag','Edep',...
        'TwinBias_Q',18573.73,...
        'SysBudget',66,...
        'pullFlag',99,...
        'NonPoissonScaleFactor',1,...
        'FakeInitFile',FakeInitFile,...
        'PixList',1:136,...
        'DopplerEffectFlag','FSD'};
    
    T = RunAnalysis(RunAnaArg{:});
    T.chi2 = chi2;
    %% settings sterile class
    SterileArg = {'RunAnaObj',T,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
        'nGridSteps',nGridSteps,...
        'SmartGrid','OFF',...
        'RecomputeFlag','OFF',...
        'SysEffect','all',...
        'RandMC','OFF',...
        'range',40,...
        'LoadGridArg',{'ExtmNu4Sq','ON','mNu4SqTestGrid',2}};
    
    S = SterileAnalysis(SterileArg{:});
    S.GridSearch(S.LoadGridArg{:},'FixmNuSq',FixmNuSq_all(i));
end