--------------------------------------------------------------
Tritium Beta Decay Spectrum with following properties:
--------------------------------------------------------------
   - EndPoint: 18573.7 eV 
   - (Kinetic) Energy Range: [18484.1,18709.1] eV - 2251 bins 
   - 2 body-decay phase space + relativistic Fermi function 
   - Screening correction: OFF 
   - Finite Extention of Nucleus Charge: OFF 
   - Weak interaction finite size correction: OFF 
   - Electron-Electron Exchange correction: OFF 
   - Recoil Coulomb correction: OFF 
   - Radiative corrections: ON (type 1)
   - Weinheimer93 Phase Space: OFF
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- - - - - Neutrinos 
   - Effective Neutrino mass: 0 eV 
   - Sterile Neutrino -  mass: 0 eV - mixing: 0
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- - - - - WGTS 
   - T-T - FSD: BlindingKNM2 (activity fraction = 0.963789)
   - D-T - FSD: BlindingKNM2 (activity fraction = 0.00634896)
   - H-T - FSD: BlindingKNM2 (activity fraction = 0.029)
   - T-Decay Rate out of WGTS: 1.29342e+10 Counts in 489479 sec 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- - - - - MACE 
   - Integral Spectrum - Time Distribution: KNM2_after2ndFix 
   - Transmission Function: WGTSMACE 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- - - - - Backgrounds 
   - Flag: ON  - Type: FLAT
   - Rate: 407.209 mcps per qU (renormalized for 148 pixel)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- - - - - FPD 
   - Segmentation: OFF  
   - Mean Efficiency: 0.95  
   - Tritium e- FPD: 978.584 cps at (qU>18484.1 eV)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
--------------------------------------------------------------
