% ksn2 extract systematic contribution
% raster scan
% compare variances

%% settings that might change
nGridSteps            = 30;
DataType              = 'Twin';
range                 = 40;
freePar               = 'E0 Norm Bkg';
CL                    = chi2cdf(1,1);
%% configure RunAnalysis object

A = MultiRunAnalysis('RunList','KNM1',...
    'chi2','chi2CMShape',...
    'DataType',DataType,...
    'fixPar',freePar,...
    'NonPoissonScaleFactor',1.064,...
    'SysBudget',200,...
    'minuitOpt','min ; minos',...
    'FSDFlag','KNM2_0p1eV',...
    'ELossFlag','KatrinT2A20',...
    'AngularTFFlag','ON',...
    'SynchrotronFlag','ON',...
    'RadiativeFlag','ON',...
    'DopplerEffectFlag','FSD',...
    'BKG_PtSlope',-2.2*1e-06);
A.exclDataStart = A.GetexclDataStart(range);
%% configure Sterile analysis object
SterileArg = {'RunAnaObj',A,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',nGridSteps,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',range,...
    'ConfLevel',CL,...
    'LoadGridArg',{'ExtmNu4Sq','OFF','mNu4SqTestGrid',2}};
S = SterileAnalysis(SterileArg{:});

SysEffectsAll   = {'Stat','BkgPT','NP','FSD', 'RF_BF','Bkg','TASR','RF_EL',...
    'RF_RX','FPDeff','Stack','TCoff_OTHER','all'};

%%
S.SysEffect = 'BkgPT';
S.InterpMode = 'lin';
[Ratio,StatDomFraction,mNu4Sq,sin2t4_Stat,sin2t4_Tot,sin2t4_Sys] = S.StatOverSysKsn2('RasterScan','ON');

savedir = [getenv('SamakPath'),'ksn1ana/ksn1_Systematics/results/'];
savename = sprintf('%sksn1_ReAna_StatOverSyst_%s.mat',savedir,DataType);

if CL~=0.95
    savename = strrep(savename,'.mat',sprintf('%.2gCL.mat',CL));
end

if ~exist(savename,'file')
    save(savename,'mNu4Sq','sin2t4_Stat','sin2t4_Tot','sin2t4_Sys');
end
%%
 close all;
 GetFigure;
hold on;
plot(mNu4Sq,Ratio,'LineWidth',3);
ylabel('Variance ratio');
ylabel(sprintf('\\sigma_{syst.}^2 / \\sigma_{total}^2'))
xlabel(sprintf('{\\itm}_4^2 (eV^2)'));
set(gca,'XScale','log');
PrettyFigureFormat('FontSize',22);


