
myEffect      = 'FSD';
RecomputeFlag = 'OFF';
nTrials       =  5000;
SysBudget     = 22; % 22 = knm1 default 

% model setting
RunList   = 'KNM1';
AnaFlag   = 'StackPixel'; % FPD segmentation

RunArg = {'FSDFlag','BlindingKNM2',...
    'ELossFlag','KatrinT2',...
    'AnaFlag',AnaFlag,...
    'chi2','chi2Stat',...      % switch on later by hand
    'RunList',RunList,...
    'fixPar','E0 Norm Bkg',... % free parameter
    'DataType','Twin',...      % MC twins
    'TwinBias_Q',18573.7,...  % twin endpoint
    'SysBudget',SysBudget,...
    'RingMerge','Full',...
    'NonPoissonScaleFactor',1,...
    'AngularTFFlag','OFF'};

if strcmp(myEffect,'Bkg')
    CmArg = {'BkgCM','ON',...
        'RecomputeFlag',RecomputeFlag,...
        'nTrials',nTrials,...
        'SysEffects',struct('FSD','OFF'),...
        'PlotSaveCM','ON'};
else
    CmArg = {'BkgCM','OFF',...
        'RecomputeFlag',RecomputeFlag,...
        'nTrials',nTrials,...
        'SysEffects',struct(myEffect,'ON'),...
        };
end
%% init model
M = MultiRunAnalysis(RunArg{:});
M.chi2 = 'chi2CMShape';

%% label
plotdir = [getenv('SamakPath'),'ksn1ana/ksn1_systematics/plots/'];
MakeDir(plotdir);

if ~strcmp(myEffect,'all')
    %% calculate and plot specific covariance matrix
    M.ComputeCM(CmArg{:});
    % display and save to plots
    M.FitCM_Obj.PlotCM('qUWindowIndexMax',10,'saveplot','ON','Convergence',...
        'ON','Mode','Shape','PlotEffect',myEffect,'savedir',plotdir);
    M.FitCM_Obj.PlotCorr('qUWindowIndexMax',10,'saveplot','ON',...
        'savedir',plotdir,'savename',myEffect);
    
elseif strcmp(myEffect,'all')
    %% plot total stat + syst CM
    M.ComputeCM;
    
    % cov mat frac shape
    M.FitCM_Obj.PlotCM('qUWindowIndexMax',10,'saveplot',...
        'ON','Convergence','OFF','CovMatInput',M.FitCMFracShape,'PlotEffect','total',...
        'savedir',plotdir,'savename','FS_Uniform');
    % correlation
    M.FitCM_Obj.PlotCorr('qUWindowIndexMax',10,'saveplot',...
        'ON','CovMatInput',M.FitCMFracShape,...
        'savedir',plotdir,'savename','KNM1_FS_Uniform');
end

