%% settings
RunList               = 'KNM1';
exclDataStart         = 14;
nTrials               = 5000;
RecomputeFlag         = 'OFF';
SysEffects            = struct('TASR','ON','FSD','ON','RF_RX','ON','RF_EL','ON','RF_BF','ON','BkgShape','ON','TCoff_RAD','ON','TCoff_OTHER','ON','Stack','ON');
BkgCM                 = 'ON';

%% Init Model Object and covariance matrix object
Twin = MultiRunAnalysis('RunList',RunList,...
    'chi2','chi2Stat','DataType','Twin',...
    'exclDataStart',exclDataStart,...
    'fixPar','5 6 7 8 9 10 11',...
    'RadiativeFlag','ON',...
    'NonPoissonScaleFactor',1.064,...
    'minuitOpt','min ; minos');
Twin.ComputeCM('SysEffects',SysEffects,'BkgCM','ON');
%     'TwinBias_mnuSq', 4.8400,...

%% Display Effect
%Twin.FitCM_Obj.DisplayCMInfo

%% Plot Correlation EO/m2
%Twin.PlotFitm2e0Contours('ErrorOnModel','ON');

%% Sensitivity - Via ASimov Fit Error
% Stat
Twin.chi2='chi2Stat';Twin.ComputeCM('SysEffects',SysEffects,'BkgCM',BkgCM);
Twin.Fit; Twin.PlotFit('saveplot','png');
Rstat = Twin.FitResult;
%% CM
Twin.chi2='chi2CM';Twin.ComputeCM('SysEffects',SysEffects,'BkgCM',BkgCM);
%Twin.PlotFitCovCorMatrices('Mode','Frac');
Twin.Fit; Twin.PlotFit('saveplot','png');
Rsys  = Twin.FitResult;
% CM Shape
Twin.chi2='chi2CMShape';Twin.ComputeCM('SysEffects',SysEffects,'BkgCM',BkgCM);
%Twin.PlotFitCovCorMatrices('Mode','Shape');
Twin.Fit('CATS','OFF'); Twin.PlotFit('saveplot','png');
Rsysshape = Twin.FitResult;

%%
t = PrintTable('Sensitivity Fit Results');
t.addRow('Parameter','Value','Error','Value','Error','Value','Error');
t.addRow('m^2_\beta \, (eV^2)',...
    sprintf('%.2f',Rstat.par(1)),sprintf('%.2f',Rstat.err(1)),...
    sprintf('%.2f',Rsys.par(1)),sprintf('%.2f',Rsys.err(1)),...
    sprintf('%.2f',Rsysshape.par(1)),sprintf('%.2f',Rsysshape.err(1)));
t.addRow('E_{0,eff}  \, (eV)',...
    sprintf('%.2f',Twin.ModelObj.Q_i+Rstat.par(2)),sprintf('%.2f',Rstat.err(2)),...
    sprintf('%.2f',Twin.ModelObj.Q_i+Rsys.par(2)),sprintf('%.2f',Rsys.err(2)),...
    sprintf('%.2f',Twin.ModelObj.Q_i+Rsysshape.par(2)),sprintf('%.2f',Rsysshape.err(2)));
t.addRow('\rm{Background}  \, (mcps)',...
    sprintf('%.2f',(Twin.ModelObj.BKG_RateSec_i + Rstat.par(3))*1e3),sprintf('%.2f',Rstat.err(3)*1e3),...
    sprintf('%.2f',(Twin.ModelObj.BKG_RateSec_i + Rsys.par(3))*1e3),sprintf('%.2f',Rsys.err(3)*1e3),...
    sprintf('%.2f',(Twin.ModelObj.BKG_RateSec_i + Rsysshape.par(3))*1e3),sprintf('%.2f',Rsysshape.err(3)*1e3));
t.addRow('\rm{Normalization}',...
    sprintf('%.2f',Rstat.par(4)+1),sprintf('%.2f',Rstat.err(3)),...
    sprintf('%.2f',Rsys.par(4)+1),sprintf('%.2f',Rsys.err(3)),...
    sprintf('%.2f',Rsysshape.par(4)+1),sprintf('%.2f',Rsysshape.err(3)));
t.addRow('','','','','','','');
t.addRow('\chi^2/dof',...
    [sprintf('%.2f',Rstat.chi2min) '/' sprintf('%.2f',Rstat.dof)],'',...
    [sprintf('%.2f',Rsys.chi2min) '/' sprintf('%.2f',Rsys.dof)],'',...
    [sprintf('%.2f',Rsysshape.chi2min) '/' sprintf('%.2f',Rsysshape.dof)],'');
t.display;
t.HasHeader = true;
t.Format = 'tex';
t.Caption = sprintf('Fit Results  - Fitter = %s - Range = [%.1f - %.1f] eV',...
    Twin.fitter,Twin.ModelObj.qU(Twin.exclDataStart),Twin.ModelObj.qU(end));
t.print;