% Uniform fit on KNM2 data/twins
% March 2022, Lisa

chi2 = 'chi2CMShape';%Stat';
qURange  = [95,20];
NonPoissonScaleFactor = 1.112;
fitter = 'minuit';
Chi2Profile = 'ON';
% create mini short cut file for plotting
savedir = [getenv('SamakPath'),'knm2ana/knm2_qUScan/results/'];
savename = sprintf('%sknm2_qUScan_Mini_%.0feV_to_%.0feV_%s_NP%.3f_%s_profilechi2%s.mat',...
    savedir,qURange(1),qURange(2),chi2,NonPoissonScaleFactor,fitter,Chi2Profile);

if exist(savename,'file')
    load(savename);
else
    SigmaSq =  0.0124+0.0025;
    BKG_PtSlope = 3*1e-06;
    ELossFlag = 'KatrinT2A20';
    FSDFlag = 'KNM2_0p1eV';
    SysBudget = 40;
    
    RunAnaArg = {'RunList','KNM2_Prompt',...
        'DataType','Real',...
        'fixPar','mNu E0 Bkg Norm',...
        'RadiativeFlag','ON',...
        'DopplerEffectFlag','FSD',...
        'fitter',fitter,...
        'minuitOpt','min ; minos',...
        'FSDFlag',FSDFlag,...
        'ELossFlag',ELossFlag,...
        'SysBudget',SysBudget,...
        'AnaFlag','StackPixel',...
        'chi2',chi2,...
        'TwinBias_Q',18573.7,...
        'NonPoissonScaleFactor',NonPoissonScaleFactor,...
        'FSD_Sigma',sqrt(SigmaSq),...
        'TwinBias_FSDSigma',sqrt(SigmaSq),...
        'BKG_PtSlope',BKG_PtSlope,...
        'TwinBias_BKG_PtSlope',BKG_PtSlope};
    D = MultiRunAnalysis(RunAnaArg{:});
    range = 40;               % fit range in eV below endpoint
    D.exclDataStart = D.GetexclDataStart(range); % find correct data, where to cut spectrum
    %% extra label for qU-scan with "wrong" energy loss function
    saveStr = sprintf('_%s_BkgPt%.3gmuCpsPerkeV',ELossFlag,BKG_PtSlope.*1e6);
    %%
    % qU Scan
 [parqU, errqU, chi2qU, dofqU] = ...
        D.qUScan('qURange',qURange,'RecomputeFlag','OFF','Chi2Profile',Chi2Profile,...
        'RefLine',40,...
        'saveplot','OFF','ErrorBarScaling',1,'saveStr',saveStr,'HoldOn','OFF','CorrMean','OFF');
    
    
    save(savename,'parqU','errqU','chi2qU','dofqU','D','RunAnaArg');
end
%%

  saveStr = sprintf('_%s_BkgPt%.3gmuCpsPerkeV','KatrinT2A20',3);
 [parqU, errqU, chi2qU, dofqU,e1,pref,err_mNuSq_Asym] = ...
        D.qUScan('qURange',qURange,'RecomputeFlag','OFF','Chi2Profile',Chi2Profile,...
        'RefLine',40,...
        'saveplot','ON','ErrorBarScaling',1,'saveStr',saveStr,'HoldOn','ON1','CorrMean','OFF');
    
    
    
