%% 1. Step: Initialize SensitivityStudy Object 

%% KATRIN SETTINGS
TimeDays      = 900;
TimeSec       = (TimeDays*24*60*60*(124/148));
MACE_Ba_T     = 7*1e-04;        % B-field AP
WGTS_B_T      = 0.7*3.6;        % B-field WGTS
MACE_Bmax_T   = 0.7*6; 
Q_i           = 18575;          % Endpoint
range         = 30;             % Max range, V
TD            = 'MTDcreator';   % Type of MTD
%Anchor6GValue = 430e-3;         % Background @6G in AP

FPD_MeanEff   = 0.95;
%% COMPUTATION SETTINGS
RecomputeFlag = 'ON';
Scan          = 'ON';
ScanPrcsn     = 0.01;
mNuStop       = 1;                
PlotFit       = 'OFF';  

% SYSTEMATICS
SysBudget     = '09';
chi2          = 'chi2CM';
SysEffect     = 'all';
InputArg = {...
    'TimeSec',TimeSec,...
    'Q_i',Q_i,...
    'MACE_Ba_T',MACE_Ba_T,...
    'WGTS_B_T',WGTS_B_T,...
    'MACE_Bmax_T',MACE_Bmax_T,...
    'SysEffect',SysEffect,...
    'SysBudget',SysBudget,...
    'TD',TD,...
    'TD_BkgFraction',20/100,...
    'TD_NuMassFactor',60/100,...
    'TD_BqU',[5 10 20],...
    'range',range,...
    'Scan',Scan,...
    'ScanPrcsn',ScanPrcsn,...
    'mNuStop',mNuStop,...
    'RecomputeFlag',RecomputeFlag...
    'PlotFit',PlotFit,...
    'FPD_MeanEff',FPD_MeanEff,...
    'TD',TD,...
    'AnchorBkg6G',AnchorBkg6G,...
    };

mNu90_stat = 0;
mNu90_sys  = 0;

    Sstat=SensitivityStudy(InputArg{:},'chi2','chi2Stat');
    Ssys=SensitivityStudy(InputArg{:},'chi2',chi2);
    [~, ~, ~, ~,~,mNu90_stat,~] = Sstat.NuMassScan;    
    [~, ~, ~, ~,~,mNu90_sys,~] = Ssys.NuMassScan;    
    
disp(sqrt(mNu90_stat))
disp(sqrt(mNu90_sys))
% 
% S = SensitivityStudy('SysBudget','09',...
%                 'TD_BkgFraction',20/100,...
%                 'TD_NuMassFactor',60/100,...
%                 'TD_BqU',[5 10],...
%                 'chi2','chi2Stat','TimeSec',900*86400,...
%                 'MACE_Ba_T',7*1e-4,...
%                 'WGTS_B_T',3.6*0.7,...
%                 'MACE_Bmax_T',6*0.7,...
%                 'Scan','ON','ScanPrcsn',0.01,...
%                 'AnchorBkg6G',430e-3,...
%                 'range',30,...
%                 'RecomputeFlag','ON',...
%                 'Q_i',18575);
%  S.NuMassScan;
%             