WorkFunBias = 3;
MACE_Ba_T = 7*1e-04;
WGTS_B_T  = 0.7*3.6;
TimeSec   = 3*365*24*60*60;

range = 30;
TD = sprintf('Sensitivity_%.0feV_Ba%.0fG',range,MACE_Ba_T*1e4);
SysEffect = 'all';
SysBudget = '01';
ScanPrcsn = 0.02; % Scan Precision (Acceptable Delta chi2)
mNuStop = 0.6; % Stop mNu eV for neutrino mass scan

[~, parStat, ~, ~,~,mNu90Stat,~] = NuMassScan_SensitivityNominal('WorkFunBias',0,...
    'chi2','chi2Stat',...
    'range',range,'MACE_Ba_T',MACE_Ba_T,'WGTS_B_T',WGTS_B_T,...
    'ScanPrcsn',ScanPrcsn,'mNuStop',mNuStop,'plotFit','OFF',...
    'TimeSec',TimeSec);

[~, parCM, ~, ~,~,mNu90CM,~] = NuMassScan_SensitivityNominal('WorkFunBias',0,...
    'chi2','chi2CM','SysEffect',SysEffect,'SysBudget',SysBudget,...
    'range',range,'MACE_Ba_T',MACE_Ba_T,'WGTS_B_T',WGTS_B_T,...
    'ScanPrcsn',ScanPrcsn,'mNuStop',mNuStop,'plotFit','OFF',...
    'TimeSec',TimeSec);

% with a work function Bias
[~, parStat_WF, ~, ~,~, mNu90Stat_WFbias,~] = NuMassScan_SensitivityNominal('WorkFunBias',WorkFunBias,...
    'chi2','chi2Stat',...
    'range',range,'MACE_Ba_T',MACE_Ba_T,'WGTS_B_T',WGTS_B_T,...
    'ScanPrcsn',ScanPrcsn,'mNuStop',mNuStop,'plotFit','OFF',...
    'TimeSec',TimeSec);

[~, parCM_WF, ~, ~,~, mNu90CM_WFbias,~] = NuMassScan_SensitivityNominal('WorkFunBias',WorkFunBias,...
    'chi2','chi2CM','SysEffect',SysEffect,'SysBudget',SysBudget,...
    'range',range,'MACE_Ba_T',MACE_Ba_T,'WGTS_B_T',WGTS_B_T,...
    'ScanPrcsn',ScanPrcsn,'mNuStop',mNuStop,'plotFit','OFF',...
    'TimeSec',TimeSec);
