% ksn2 calculate chi2 grid search
%% settings that might change
chi2 = 'chi2Stat+';
DataType = 'Twin';
nGridSteps = 25;
range = 40;
NonPoissonScaleFactor = 1+1.*0.112;
%% configure RunAnalysis object
RunAnaArg = {'RunList','KNM2_Prompt',...
    'DataType',DataType,...
    'fixPar','E0 Norm Bkg',...%free par
    'SysBudget',40,...
    'fitter','minuit',...
    'minuitOpt','min;migrad',...
    'RadiativeFlag','ON',...
    'FSDFlag','KNM2_0p1eV',...
    'ELossFlag','KatrinT2A20',...
    'AnaFlag','StackPixel',...
    'chi2',chi2,...
    'NonPoissonScaleFactor',NonPoissonScaleFactor,...
    'FSD_Sigma',sqrt(0.0124+0.0025),...
    'TwinBias_FSDSigma',sqrt(0.0124+0.0025),...
    'TwinBias_Q',18573.7,...
    'PullFlag',99,...;%99 = no pull
    'BKG_PtSlope',3*1e-06,...
    'TwinBias_BKG_PtSlope',3*1e-06,...
    'DopplerEffectFlag','FSD'};
A = MultiRunAnalysis(RunAnaArg{:});
%% configure Sterile analysis object
SterileArg = {'RunAnaObj',A,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',nGridSteps,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',range};

%%
S = SterileAnalysis(SterileArg{:});
%%
%S.GridSearch;
S.InterpMode = 'spline';
%%
NPfacAlt = 1+5.*0.112;
CLalt = 98;
Colors = colormap('winter');

% Ksn2 - with alternative NP for 95%% CL
S.RunAnaObj.NonPoissonScaleFactor = NPfacAlt;
S.LoadGridFile;
S.Interp1Grid('RecomputeFlag','ON');
p2 = S.ContourPlot('CL',95,'Color',Colors(255,:),'HoldOn','OFF','SavePlot','OFF');

% Ksn2 - default NP for 2 CL
S.RunAnaObj.NonPoissonScaleFactor = 1.1121;
S.LoadGridFile;
S.Interp1Grid('RecomputeFlag','ON');
p1 = S.ContourPlot('Color',rgb('DodgerBlue'),'HoldOn','ON','SavePlot','OFF');
p11 = S.ContourPlot('CL',CLalt,'Color',rgb('DodgerBlue'),'HoldOn','ON','SavePlot','OFF','LineStyle',':');

xlim([5e-03,0.5])
%
leg = legend([p1,p11,p2],...
     sprintf('{\\itB}_{NP} = 11.2%% at 95%% C.L. (KSN-2 default)'),...
     sprintf('{\\itB}_{NP} = 11.2%% at %.3g%% C.L.',CLalt),...
      sprintf('{\\itB}_{NP} = %.1f%% at 95%% C.L.',(NPfac-1)*100));
PrettyLegendFormat(leg);
%

%% save
plotdir = [getenv('SamakPath'),'ksn2ana/ksn2_ModelBlinding/plots/'];
plotname = sprintf('%sksn2_ModelBlindingNP_Convert2CL.png',plotdir);
print(plotname,'-dpng','-r300');
fprintf('save plot to %s \n',plotname);