% Calculate KATRIN Design Report Sensitivities
%% Settings
TimeSec = 3*365*24*60*60;
MACE_Ba_T = 3*1e-04;
WGTS_B_T = 3.6;
MACE_Bmax_T = 6;
BKG_RateSec = 0.01; 
Q_i = 18575;
TD = 'DR30';
range = 30;
Scan = 'ON';
PlotFit = 'OFF'; %only used when Scan ON
SysBudget = '05';
RecomputeFlag = 'OFF';
ELossFlag = 'Abdurashitov';
recomputeRF = 'OFF';
FPD_MeanEff = 0.90;
chi2name = 'chi2Stat';
FPD_ROIlow = 14;
%% Init Sensitivty Class Object
Arg = {'TimeSec',TimeSec,...
    'Q_i',Q_i,...
    'chi2',chi2name,...
    'MACE_Ba_T',MACE_Ba_T,...
    'WGTS_B_T',WGTS_B_T,...
    'MACE_Bmax_T',MACE_Bmax_T,...
    'TD',TD,...
    'BKG_RateSec',BKG_RateSec,...
    'Scan',Scan,...
    'PlotFit',PlotFit,...
    'SysBudget',SysBudget,...
    'recomputeRF',recomputeRF,...
    'ELossFlag',ELossFlag,...
    'FPD_MeanEff',FPD_MeanEff,...
    'FPD_ROIlow',FPD_ROIlow,...
    'AnchorBkg6G',''};

S = SensitivityStudy(Arg{:});
%% Calculate Sensitivites
S.RecomputeFlag = 'OFF'; % switch ON, in case never calculated before (or you wish to recompute)
S.NuMassScan_SystematicsLoop; 
S.NuMassScan_SensitivityNominal_Nplus1Systematics_Loop;
%% Sensitivites Stored in Variables
S.MultimNu90      % individual contributions
S.MultimNu90Stack % stat, stat+tc, stat+tc+fsd,...
%% Bar Plot: ONLY works when calculated and in advance!
S.PlotRFBreakdownBars('Ranges',S.range); % only 1 range
S.PlotSysBreakdownBars('Ranges',S.range);



                  