% compare contours from
% - full grid search (sint4^2, m4^2) --> 2 parameters of interest
% - raster scan: pretend that we know m4^2 (sint4^2) --> 1 parameter of interest
% technical difference is only the critical DeltaChi^2

%% settings for runanalysis
DataType = 'Twin';
range = 40;
freePar = 'E0 Norm Bkg';

RunAnaArg = {'RunList','KNM1',...
    'fixPar',freePar,...
    'DataType',DataType,...
    'FSDFlag','SibilleFull',...
    'ELossFlag','KatrinT2',...
    'AnaFlag','StackPixel',...
    'chi2','chi2Stat',...
    'ROIFlag','Default',...
    'SynchrotronFlag','ON',...
    'AngularTFFlag','OFF',...
    'ISCSFlag','Edep',...
    'TwinBias_Q',18573.73,...
    'SysBudget',24,...
    'pullFlag',99,...
    'NonPoissonScaleFactor',1};

T = MultiRunAnalysis(RunAnaArg{:});
T.chi2 = 'chi2CMShape';
%% settings sterile class
SterileArg = {'RunAnaObj',T,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',50,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',range,...
    'ConfLevel',95};

S = SterileAnalysis(SterileArg{:});

S.LoadGridFile('CheckSmallerN','ON');
S.Interp1Grid('RecomputeFlag','ON');
% plot data
pGrid = S.ContourPlot('CL',S.ConfLevel,'HoldOn','OFF','Color',rgb('DodgerBlue'),...
    'LineStyle','-','BestFit','OFF','PlotSplines','OFF');
pRaster = S.ContourPlot('CL',S.ConfLevel,'HoldOn','ON','Color',rgb('Orange'),...
    'LineStyle','-.','BestFit','OFF','PlotSplines','OFF','RasterScan','ON');

 leg = legend([pGrid,pRaster],sprintf('Grid search \\chi^2_{crit.} = %.2f',GetDeltaChi2(S.ConfLevel,2)),...
    sprintf('Raster scan \\chi^2_{crit.} = %.2f',GetDeltaChi2(S.ConfLevel,1)));
leg.Title.String = sprintf('%s - %.0f eV range - %.0f%% C.L.',...
    S.GetPlotTitle('Mode','data'),range,S.ConfLevel);
leg.Title.FontWeight = 'normal';
title('');
ylim([1 2e3]);
xlim([6e-03 0.5]);
%%
plotname = [S.DefPlotName,'_CompareGridSearchRasterScan.png'];
print(gcf,plotname,'-dpng','-r400');
plotname = [S.DefPlotName,'_CompareGridSearchRasterScan.pdf'];
export_fig(gcf,plotname);
fprintf('save plot to %s \n',plotname)
