systematics = struct(...
    'RF_EL','ON',...
    'RF_BF','ON',...
    'RF_RX','ON',...
    'FSD','ON',...
    'TASR','ON',...
    'TCoff_RAD','ON',...
    'TCoff_OTHER','ON',...
    'DOPoff','OFF');
CMoptions   = {
    'WGTS_TASR_RelErr',0.005,...
    'FSDNorm_RelErr',0.01,...
    'FSDShapeGS_RelErr',0.04,...
    'FSDShapeES_RelErr',0.18,...
    'MACE_Ba_T_RelErr',0.01,...
    'MACE_Bmax_T_RelErr',0.002,...
    'WGTS_B_T_RelErr',0.025,...
    'WGTS_CD_MolPerCm2_RelErr',0.05,...
    'ISXsection_RelErr',0.02,...
    'BkgCM','OFF',...
    'Stack','OFF'...
    };

% KITNUSCAN
SPR1=MultiRunAnalysis(...
    'DataType','Real',...
    'RunList','KITNUSCAN',...
    'exclDataStart',2,...
    'fixPar','1 5 6 7 8 9 10',...
    'chi2','chi2CMShape',...
    'ELossFlag','KatrinD2',...
    'StackTolerance',0.2,...
    'NonPoissonScaleFactor',1.5,...
    'Debug','OFF');
SPR1.ComputeCM('RecomputeFlag','OFF','SysEffects',systematics,CMoptions{:});
SPR1.Fit('CATS','OFF');

% March132019
SPR2=MultiRunAnalysis(...
    'DataType','Real',...
    'RunList','March132019',...
    'exclDataStart',2,...
    'fixPar','1 5 6 7 8 9 10',...
    'chi2','chi2CMShape',...
    'ELossFlag','KatrinD2',...
    'StackTolerance',0.2,...
    'NonPoissonScaleFactor',1.5,...
    'Debug','OFF');
SPR2.ComputeCM('RecomputeFlag','OFF','SysEffects',systematics,CMoptions{:});
SPR2.Fit('CATS','OFF');

% March242019
SPR3=MultiRunAnalysis(...
    'DataType','Real',...
    'RunList','March132019',...
    'exclDataStart',2,...
    'fixPar','1 5 6 7 8 9 10',...
    'chi2','chi2CMShape',...
    'ELossFlag','KatrinD2',...
    'StackTolerance',0.2,...
    'NonPoissonScaleFactor',1.5,...
    'Debug','OFF');
SPR3.ComputeCM('RecomputeFlag','OFF','SysEffects',systematics,CMoptions{:});
SPR3.Fit('CATS','OFF');

%% Summary Plot
fig1 = figure(1);
set(fig1, 'Units', 'normalized', 'Position', [0.1, 0.1, 0.8, 0.8]);

% SPR3
PlotCM = SPR3.FitCMShape;
h13=errorbar(SPR3.RunData.qU-SPR3.ModelObj.Q_i,...
    SPR3.RunData.TBDIS./SPR3.ModelObj.qUfrac./SPR3.ModelObj.TimeSec,...
    SPR3.RunData.TBDISE./SPR3.ModelObj.qUfrac./SPR3.ModelObj.TimeSec,...
    'ko','MarkerSize',3,'MarkerEdgeColor' , rgb('IndianRed'));
h13.MarkerSize = 5; h13.CapSize = 0;h13.LineStyle= 'none';h13.LineWidth= 2;legend hide
hold on
% hfit1 = boundedline(SPR3.ModelObj.qU-SPR3.ModelObj.Q_i,...
%     SPR3.ModelObj.TBDIS./SPR3.ModelObj.qUfrac./SPR3.ModelObj.TimeSec,...
%     diag(sqrt(PlotCM))./SPR3.ModelObj.qUfrac./SPR3.ModelObj.TimeSec,...
%     'alpha','cmap',rgb('IndianRed'));
[ll3 la3]= boundedline(SPR3.ModelObj.qU-SPR3.ModelObj.Q_i,...
    SPR3.ModelObj.TBDIS./SPR3.ModelObj.qUfrac./SPR3.ModelObj.TimeSec,...
    sqrt(diag(PlotCM))./SPR3.ModelObj.qUfrac./SPR3.ModelObj.TimeSec,...
    'alpha','cmap',rgb('IndianRed'));
ll3.LineStyle='--'; legend hide

% % SPR2
% PlotCM = SPR2.FitCMShape;
% h1=errorbar(SPR2.RunData.qU-SPR2.ModelObj.Q_i,...
%     SPR2.RunData.TBDIS./SPR2.ModelObj.qUfrac./SPR2.ModelObj.TimeSec,...
%     SPR2.RunData.TBDISE./SPR2.ModelObj.qUfrac./SPR2.ModelObj.TimeSec,...
%     'ko','MarkerSize',3,'MarkerEdgeColor' , [0 0 0]);
% h1.MarkerSize = 5; h1.CapSize = 0;h1.LineStyle= 'none';h1.LineWidth= 2;legend hide
% hold on
% hfit1 = boundedline(SPR2.ModelObj.qU-SPR2.ModelObj.Q_i,...
%     SPR2.ModelObj.TBDIS./SPR2.ModelObj.qUfrac./SPR2.ModelObj.TimeSec,...
%     diag(sqrt(PlotCM))./SPR2.ModelObj.qUfrac./SPR2.ModelObj.TimeSec,...
%     'alpha','cmap',rgb('IndianRed'));
% [ll la]= boundedline(SPR2.ModelObj.qU-SPR2.ModelObj.Q_i,...
%     SPR2.ModelObj.TBDIS./SPR2.ModelObj.qUfrac./SPR2.ModelObj.TimeSec,...
%     sqrt(diag(PlotCM))./SPR2.ModelObj.qUfrac./SPR2.ModelObj.TimeSec,...
%     'alpha','cmap',rgb('IndianRed'));
% ll.LineStyle='--'; legend hide


% SPR1
PlotCM = SPR1.FitCMShape;
h11=errorbar(SPR1.RunData.qU-SPR1.ModelObj.Q_i,...
    SPR1.RunData.TBDIS./SPR1.ModelObj.qUfrac./SPR1.ModelObj.TimeSec,...
    SPR1.RunData.TBDISE./SPR1.ModelObj.qUfrac./SPR1.ModelObj.TimeSec,...
    'ko','MarkerSize',3,'MarkerEdgeColor' , rgb('SteelBlue'));
h11.MarkerSize = 5; h11.CapSize = 0;h11.LineStyle= 'none';h11.LineWidth= 2;legend hide
hold on
% hfit1 = boundedline(SPR1.ModelObj.qU-SPR1.ModelObj.Q_i,...
%     SPR1.ModelObj.TBDIS./SPR1.ModelObj.qUfrac./SPR1.ModelObj.TimeSec,...
%     diag(sqrt(PlotCM))./SPR1.ModelObj.qUfrac./SPR1.ModelObj.TimeSec,...
%     'alpha','cmap',rgb('CadetBlue'));
[ll1 la1]= boundedline(SPR1.ModelObj.qU-SPR1.ModelObj.Q_i,...
    SPR1.ModelObj.TBDIS./SPR1.ModelObj.qUfrac./SPR1.ModelObj.TimeSec,...
    sqrt(diag(PlotCM))./SPR1.ModelObj.qUfrac./SPR1.ModelObj.TimeSec,...
    'alpha','cmap',rgb('CadetBlue'));
ll1.LineStyle='--'; legend hide
hold off
%
axis([1.1*min(SPR3.ModelObj.qU-SPR3.ModelObj.Q) 1.1*max(SPR3.ModelObj.qU-SPR3.ModelObj.Q)  SPR3.ModelObj.BKG_RateSec/2 max(SPR3.RunData.TBDIS./SPR3.ModelObj.qUfrac./SPR3.ModelObj.TimeSec)*1.1 ]);

% Axis
xlabel(sprintf('retarding potential - %.1f (V)',SPR3.ModelObj.Q_i),'FontSize',16);
ylabel('rate (cps)','FontSize',16);
set(gca, 'YScale', 'log');
% Title
title(sprintf('KATRIN - m_{\\nu} Test Scans - March 2019 (Samak)'));
% Legend
l13 = 'data 47x1h - \rho d = 19e16 mol/cm^2';
l23 = ('model + uncertainty - \rho d = 19e16 mol/cm^2');
l11 = 'data 10x2h - \rho d = 2e16 mol/cm^2';
l21 = ('model + uncertainty - \rho d = 2e16 mol/cm^2');
xlim([-100,+51]); ylim([0.1,1000]);
a = legend([h13 la3 h11 la1],l13,l23,l11,l21,'Location','NorthEast','Box','off'); a.String=a.String(1:4);
set(a,'Color',rgb('White'),'EdgeColor',rgb('White'),'Box', 'on');
% Polishing
grid on
PrettyFigureFormat;
set(gca,'YMinorTick','on');
set(gca,'TickLength',[0.01 0.01]);
set(gca,'YTick',[1,10,100,1000]);
set(gca,'FontSize',24);



