% calculate and display Non-Poisson factor

RunList = 'KNM2_RW3';
range = 40;
RunAnaArg = {'RunList',RunList,...
    'FSDFlag','BlindingKNM2',...
    'ELossFlag','KatrinT2',...
<<<<<<< HEAD
    'AnaFlag','StackPixel',...
    'chi2','chi2Stat',...
    'DataType','Real',...
    'fixPar','E0 Bkg Norm'};
=======
    'AnaFlag','Ring',...
    'chi2','chi2Stat',...
    'DataType','Real',...
    'fixPar','E0 Bkg Norm',...
    'RingMerge','Full'};
>>>>>>> 2680d1afe0066666933d7782d14d252046b5598f
%% set up model
A = MultiRunAnalysis(RunAnaArg{:});
A.exclDataStart = A.GetexclDataStart(range);

%% calculate NP factor
<<<<<<< HEAD
GetNPfactor(A,'SlopeCorr','ON','RecomputeFlag','OFF','SanityPlot','OFF');
=======
GetNPfactor(A,'SlopeCorr','OFF','RecomputeFlag','OFF','SanityPlot','ON');
>>>>>>> 2680d1afe0066666933d7782d14d252046b5598f
%% result
fprintf('%s - Non Poisson background rate contribution = %.2f %% \n',strrep(A.RunData.RunName,'_',' '),(A.NonPoissonScaleFactor-1)*100)