% calculate and display Non-Poisson factor
range = 40;
SigmaSq =  0.0124+0.0025;
BKG_PtSlope = 3*1e-06;

RunAnaArg = {'RunList','KNM2_Prompt',...
    'DataType','Real',...
    'fixPar','mNu E0 Bkg Norm',...
    'RadiativeFlag','ON',...
    'minuitOpt','min ; minos',...
    'FSDFlag','KNM2_0p1eV',...
    'ELossFlag','KatrinT2A20',...
    'SysBudget',40,...
    'AnaFlag','StackPixel',...
    'chi2','chi2Stat',...
    'NonPoissonScaleFactor',1,...
    'FSD_Sigma',sqrt(SigmaSq),...
    'BKG_PtSlope',BKG_PtSlope,...
    'DopplerEffectFlag','FSD'};

%% set up model
A = MultiRunAnalysis(RunAnaArg{:});
A.exclDataStart = A.GetexclDataStart(range);

%% calculate NP factor
%GetNPfactor(A,'SlopeCorr','OFF','RecomputeFlag','ON','SanityPlot','ON');
 [NPfactor, NPfactorErr]=  GetNPfactor(A,'SlopeCorr','ON','RecomputeFlag','ON','SanityPlot','ON');

%% result
fprintf('%s - Non Poisson background rate contribution = (%.2f +- %.2f) %% \n',strrep(A.RunData.RunName,'_',' '),(NPfactor-1)*100,(NPfactorErr)*100)