% plot ringwise NP factor
% based on KNM2 runs
% October 2019, Lisa

RunList = 'KNM2_Prompt';

exclDataStart= 12;
chi2 = 'chi2Stat';

% read data and set up model
CommonArg = {'RunList',RunList,...
    'chi2','chi2Stat','DataType','Real',...
    'exclDataStart',exclDataStart,...
    'fixPar','Norm E0 Bkg',...
    'RadiativeFlag','ON',...
    'minuitOpt','min ; minos',...
    'FSDFlag','BlindingKNM2',...
    'ELossFlag','KatrinT2',...
    'SysBudget',22,...
    'AnaFlag','Ring',...
    'RingMerge','Full',...
    'chi2',chi2};

R = MultiRunAnalysis(CommonArg{:});
%% get NP factor
GetNPfactor(R,'SanityPlot','ON','RecomputeFlag','ON');

