% KNM-1 chi2 profile
%% settings
RunList = 'KNM1';
range   = 40;         % 40eV range = 27 subruns
chi2 = 'chi2CMShape';
% Init Model Object and covariance matrix object
Real = MultiRunAnalysis('RunList',RunList,...
    'chi2',chi2,...
    'DataType','Real',...
    'fixPar','mNu E0 Norm Bkg',... free parameter
    'RadiativeFlag','ON',...
    'NonPoissonScaleFactor',1.064,...
    'minuitOpt','min ; minos',...
    'FSDFlag','Sibille0p5eV',...
    'ELossFlag','KatrinT2',...
    'SysBudget',22,...
    'AngularTFFlag','OFF',...
    'DopplerEffectFlag','FSD');
Real.exclDataStart = Real.GetexclDataStart(range);

%% Get Covariance Matrix
Real.ResetFitResults;
Real.FitResult.par(1) = -0.5;
ScanResults = Real.GetAsymFitError('Mode','Uniform','ParScanMax',1.5,'nFitMax',20);
%%
close all
mNuSq =[flipud(ScanResults.ParScan(:,2));ScanResults.ParScan(2:end,1)];
Chi2 = [flipud(ScanResults.chi2min(:,2));ScanResults.chi2min(2:end,1)];

plot(mNuSq,Chi2,':');