% calculate chi^2 for KNM1 and KNM2 using best fit parameter of COMMON fit
DataType = 'Real';
chi2 = 'chi2CMShape';
mNuSqCommon = 0.11;
% KNM1
savefile = [getenv('SamakPath'),sprintf('knm2ana/knm2_Combination/results/knm2_Combination_Chi2CommonPar.mat')];

% if exist(savefile,'file')

%% knm1
range   = 40;         % 40eV range = 27 subruns
Real = MultiRunAnalysis('RunList','KNM1',...
    'chi2',chi2,...
    'DataType',DataType,...
    'fixPar','mNu E0 Norm Bkg',... free parameter
    'RadiativeFlag','ON',...
    'NonPoissonScaleFactor',1.064,...
    'minuitOpt','min ; minos',...
    'FSDFlag','Sibille0p5eV',...
    'ELossFlag','KatrinT2',...
    'SysBudget',22,...
    'AngularTFFlag','OFF',...
    'DopplerEffectFlag','OFF');
Real.exclDataStart = Real.GetexclDataStart(range);
Real.Fit;
TBDIS_d = Real.RunData.TBDIS(Real.exclDataStart:end);
FitResult_1 = Real.FitResult;

% check
Real.ModelObj.ComputeTBDDS(...
    'mSq_bias',Real.FitResult.par(1),...
    'E0_bias',Real.FitResult.par(2),...
    'B_bias',Real.FitResult.par(3),...
    'N_bias',Real.FitResult.par(4));
Real.ModelObj.ComputeTBDIS;
TBDIS_m1     = Real.ModelObj.TBDIS(Real.exclDataStart:end);
CovMatShape = Real.FitCMShape(Real.exclDataStart:end,Real.exclDataStart:end);
chi2min_1    = chi2func(TBDIS_d,TBDIS_m1,CovMatShape);

% calculate for common best fit par
Real.ModelObj.ComputeTBDDS(...
    'mSq_bias',mNuSqCommon,...
    'E0_bias',Real.FitResult.par(2),...
    'B_bias',Real.FitResult.par(3),...
    'N_bias',Real.FitResult.par(4));
Real.ModelObj.ComputeTBDIS;
TBDIS_mCommon     = Real.ModelObj.TBDIS(Real.exclDataStart:end);
chi2min_common   = chi2func(TBDIS_d,TBDIS_mCommon,CovMatShape);

save(savefile,'chi2min_1','chi2min_common','TBDIS_d','TBDIS_m1','TBDIS_mCommon','FitResult_1');

%% knm2

freePar               = 'mNu E0 Bkg Norm';
AnaFlag               = 'StackPixel';
RingMerge             = 'Full';%'None'; %only relevand when AnaFlag = Ring
DopplerEffectFlag     = 'FSD';
BKG_PtSlope           = 3*1e-06;
TwinBias_BKG_PtSlope  = 3*1e-06;
FSDFlag               = 'KNM2';
PullFlag              = 99;% 99 = no pull
SysBudget             = 40;
NonPoissonScaleFactor = 1.112;
SigmaSq               =  0.0124+0.0025;

% Init Model Object and covariance matrix object
RunAnaArg = {'RunList','KNM2_Prompt',...
    'DataType',DataType,...
    'fixPar',freePar,...
    'RadiativeFlag','ON',...
    'minuitOpt','min ; minos',...
    'FSDFlag',FSDFlag,...
    'ELossFlag','KatrinT2A20',...
    'SysBudget',SysBudget,...
    'AnaFlag',AnaFlag,...
    'chi2',chi2,...
    'TwinBias_Q',18573.7,...
    'NonPoissonScaleFactor',NonPoissonScaleFactor,...
    'FSD_Sigma',sqrt(SigmaSq),...
    'TwinBias_FSDSigma',sqrt(SigmaSq),...
    'RingMerge',RingMerge,...
    'PullFlag',PullFlag,...;%99 = no pull
    'BKG_PtSlope',BKG_PtSlope,...
    'TwinBias_BKG_PtSlope',TwinBias_BKG_PtSlope,...
    'DopplerEffectFlag',DopplerEffectFlag};
A = MultiRunAnalysis(RunAnaArg{:});
A.exclDataStart = A.GetexclDataStart(range);

A.Fit;
TBDIS_d2 = A.RunData.TBDIS(A.exclDataStart:end);
FitResult_2 = A.FitResult;

% check
A.ModelObj.ComputeTBDDS(...
    'mSq_bias',A.FitResult.par(1),...
    'E0_bias',A.FitResult.par(2),...
    'B_bias',A.FitResult.par(3),...
    'N_bias',A.FitResult.par(4));
A.ModelObj.ComputeTBDIS;
TBDIS_m2     = A.ModelObj.TBDIS(A.exclDataStart:end);
CovMatShape2 = A.FitCMShape(A.exclDataStart:end,A.exclDataStart:end);
chi2min_2    = chi2func(TBDIS_d2,TBDIS_m2,CovMatShape2);

% calculate for common best fit par
A.ModelObj.ComputeTBDDS(...
    'mSq_bias',mNuSqCommon,...
    'E0_bias',A.FitResult.par(2),...
    'B_bias',A.FitResult.par(3),...
    'N_bias',A.FitResult.par(4));
A.ModelObj.ComputeTBDIS;
TBDIS_mCommon2     = A.ModelObj.TBDIS(A.exclDataStart:end);
chi2min_common2   = chi2func(TBDIS_d2,TBDIS_mCommon2,CovMatShape2);

save(savefile,'chi2min_2','chi2min_common2','TBDIS_d2','TBDIS_m2','TBDIS_mCommon2','FitResult_2','-append');

% end

function chi2 = chi2func(y,m,CovMatShapeFit)
chi2 = ((y - m)')* (CovMatShapeFit  \ (y - m));
end