% compare contour with different FSDs 
% twin, stat, 40 eV
% ksn2 contour on twins without penning trap background slope for fitter
% comparison
% ksn2 calculate chi2 grid search
%% settings that might change
chi2 = 'chi2Stat';
DataType = 'Twin';
nGridSteps = 25;
range = 40;
FSDFlag = 'KNM2_0p1eV';
%% configure RunAnalysis object
if strcmp(chi2,'chi2Stat')
    NonPoissonScaleFactor = 1;
elseif  strcmp(chi2,'chi2CMShape')
    NonPoissonScaleFactor = 1.112;
end
RunAnaArg = {'RunList','KNM2_Prompt',...
    'DataType',DataType,...
    'fixPar','E0 Norm Bkg',...%free par
    'SysBudget',40,...
    'fitter','minuit',...
    'minuitOpt','min;migrad',...
    'RadiativeFlag','ON',...
    'FSDFlag',FSDFlag,...
    'ELossFlag','KatrinT2A20',...
    'AnaFlag','StackPixel',...
    'chi2',chi2,...
    'NonPoissonScaleFactor',NonPoissonScaleFactor,...
    'FSD_Sigma',sqrt(0.0124+0.0025),...
    'TwinBias_FSDSigma',sqrt(0.0124+0.0025),...
    'TwinBias_Q',18573.7,...
    'PullFlag',99,...;%99 = no pull
    'BKG_PtSlope',3e-06,...
    'TwinBias_BKG_PtSlope',3e-06,...
    'DopplerEffectFlag','FSD'};
A = MultiRunAnalysis(RunAnaArg{:});
%% configure Sterile analysis object
SterileArg = {'RunAnaObj',A,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',nGridSteps,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',range};
S = SterileAnalysis(SterileArg{:});
S.GridSearch;


%% plot

% A.FSDFlag = 'KNM2_0p1eV';
% S.LoadGridFile('CheckLargerN','OFF');
% S.Interp1Grid('maxM4Sq',38^2)
% p1 = S.ContourPlot('HoldOn','OFF');
% 
% A.FSDFlag = 'KNM2_0p1eV_cut40eV';
% S.LoadGridFile('CheckLargerN','OFF');
% S.Interp1Grid('maxM4Sq',38^2)
% p2 = S.ContourPlot('HoldOn','ON','Color',rgb('Orange'),'LineStyle','-.');
% 
% A.FSDFlag = 'KNM2';
% S.LoadGridFile('CheckLargerN','OFF');
% S.Interp1Grid('maxM4Sq',38^2)
% p3 = S.ContourPlot('HoldOn','ON','Color',rgb('ForestGreen'),'LineStyle',':');
%% save
% plotdir = sprintf('%sksn2ana/ksn2_FSDrebin/plots/',getenv('SamakPath'));
% MakeDir(plotdir);
% plotname = sprintf('%sksn2_CompareContourFSD.png',plotdir);
% print(gcf,plotname,'-dpng','-r350');
% fprintf('save plot to %s \n',plotname);

