InitFile = @ref_FakeRun_KNM2_CD84_50days; %100 column density, 50 days

% set up model, compute fake run if necessary
CommonArg = {'RunNr',1,...% has no meaning
    'DataType','Fake',...
    'FakeInitFile',InitFile,...
    'FSDFlag','BlindingKNM2',...
    'ELossFlag','KatrinT2',...
    'exclDataStart',11,... % 11==40eV range (28 subruns)
    'chi2','chi2Stat',...
    'minuitOpt','min;migrad',...
    'NonPoissonScaleFactor',1,...
    'AnaFlag','StackPixel',...
    'fixPar','mNu E0 Norm Bkg'};
M = RunAnalysis(CommonArg{:});
M.Fit;
%%
M.ModelObj.is_EOffset = -1;
M.ModelObj.InitializeRF;
M.Fit;
