function chi2 = NuMassChi2(p,X)
%
% Chi2 Function For Fit Tritium Beta Spectrum
% With Nuisance Parameters
% 
% Th. Lasserre, 2012-13
%
% Gaussian Xi2
% X = [ "column vector of bin centers"  | "column vector of data" | "column vector of uncertainties" | "... extra info" ]
% p = [ p1; p2; ... ] column vector of parameter to fit

XX=X{1};
nn = XX(:,2)~=0; % indexes of non-null bins
x = XX(nn,1);    % bin centers of non-null bins
y = XX(nn,2);    % bin content of non-null bins
z = XX(nn,3);    % uncertainties bin content of non-null bins
A = X{2};
m =  NuMassModel4par(p,A);

%chi2 = -2*sum( y - m + y.*log(m./y) );                      % Poisson deviance chi square.
chi2 = sum(( y(1:numel(x)) - m(1:numel(x))).^2 ./ z(1:numel(x)).^2);
% ...
%       + (p(2)/1e-6)^2 ...
%       + (p(3)/1e-6)^2 ...
%       + (p(4)/1e-6)^2;
%          
%     + (p(8)/aQEDe)^2 ...
%     + (p(9)/aRecCorre)^2 ...
%     + (p(10)/aECorre)^2 ...
%     + (p(11)/aCCorre)^2 ...
%     + (p(12)/aL0Corre)^2 ...
%     + (p(13)/aQCorre)^2 ...
%     + (p(14)/aSCorre)^2 ...
%     + (p(15)/aGSe)^2 ...
%     + (p(16)/aESe)^2 ...
%     + ((p(15)+p(16))/1e-10)^2 ...
%     + (p(17)/aQOffe)^2 ...
%     + (p(19)/aRbkgOffe)^2;

end