CL = 95;
range = 40;%
nGridSteps = 25;
chi2Str = 'chi2CMShape';
DataType = 'Twin';
freePar = 'E0 Bkg Norm';
RunList = 'KNM1';
SmartGrid = 'OFF';
Mode = 'New_Sterile';
Twin_mNu4Sq   = 1e2;
Twin_sin2T4   = 0.06;

SysBudget =24;
RandMC = [3:94,148:292,394:405];

if range<=40
    FSDFlag = 'Sibille0p5eV';
elseif range>40
    FSDFlag = 'SibilleFull';
end

RunAnaArg = {'RunList',RunList,...
    'fixPar',freePar,...
    'DataType',DataType,...
    'FSDFlag',FSDFlag,...
    'ELossFlag','KatrinT2',...
    'AngularTFFlag','OFF',...
    'AnaFlag','StackPixel',...
    'chi2','chi2CMShape',...
    'ROIFlag','Default',...
    'SynchrotronFlag','ON',...
    'ISCSFlag','Edep',...
    'NonPoissonScaleFactor',1.064,...
    'TwinBias_Q',18573.73,...
    'SysBudget',SysBudget,...
    'pullFlag',99};

T = MultiRunAnalysis(RunAnaArg{:});
T.exclDataStart = T.GetexclDataStart(range);

D  = repmat(T,numel(RandMC),1);
%%
for i=1:numel(RandMC)
    [~,~,~,~,savefile_tmp] = KSN1GridSearch('range',range,...
        'nGridSteps',nGridSteps,...
        'chi2',chi2Str,...
        'DataType',DataType,...
        'freePar','E0 Bkg Norm',...
        'RunList',RunList,...
        'SmartGrid',SmartGrid,...
        'RecomputeFlag','OFF',...
        'RandMC',RandMC(i),...
        'SysBudget',SysBudget,...
        'Twin_mNu4Sq',Twin_mNu4Sq,...
        'Twin_sin2T4',Twin_sin2T4);
    
    d = importdata(savefile_tmp);
    D(i).RunData.TBDIS = d.TBDIS_mc;
    D(i).SimulateStackRuns;
    D(i).ModelObj.SetFitBiasSterile(Twin_mNu4Sq,Twin_sin2T4);
    D(i).Fit
    
    if d.chi2_ref>D(i).FitResult.chi2min
        chi2_ref = D(i).FitResult.chi2min;
    else
        chi2_ref = d.chi2_ref;
    end
    
    FitResults_NoSterile = d.FitResults_Null;
    FitResults_Null = D(i).FitResult;
    %parsaveSterile(savefile_tmp,FitResults_Null,FitResults_NoSterile,chi2_ref);
    save(savefile_tmp,'FitResults_Null','FitResults_NoSterile','chi2_ref','-append');
end