%% calculate grid for ksn1 stat. + 1 syst
range = 65;
nGridSteps = 25;
chi2Str = 'chi2CMShape';
DataType = 'Twin';
freePar = 'E0 Bkg Norm';
RunList = 'KNM1';
SmartGrid = 'OFF';
CL= 95;
SysBudget = 24;
mySysEffects = {...
    'FSD',...             % final state distribution       
    'TASR',...             % tritium activity fluctuations from subrun to subrun
    'RF_EL',...            % energy-loss
    'RF_BF',...            % B-fields
    'RF_RX',...            % column Density, inel. cross ection
    'TCoff_OTHER',...      % theoretical corrections without radiative
    'Stack',...            % stacking
    'FPDeff',...           % fpd efficiecny
    'Bkg'};            
DefaultSysLeg    = {'Stat. only' ;...
    'All syst. combined';...
    'Final-state distribution';...
    'Tritium activity fluctuations';...
    'Energy-loss function';
    'Magnetic fields';...
    'Source scattering';...
    'Theoretical corrections';...
    'HV fluctuations';...
    'Detector efficiency';...
    'Background slope'};%;...
nSys = numel(mySysEffects);
%% load grid (or calculate if doesn't exist)
mnu4Sq   = cell(nSys+2,1);
sin2T4   = cell(nSys+2,1);
chi2     = cell(nSys+2,1);
chi2_ref = cell(nSys+2,1);

% stat only
[mnu4Sq{1},sin2T4{1},chi2{1},chi2_ref{1},savefile] = KSN1GridSearch('range',range,...
    'nGridSteps',nGridSteps,...
    'chi2','chi2Stat',...
    'DataType',DataType,...
    'freePar',freePar,...
    'RunList',RunList,...
    'SmartGrid',SmartGrid,...
    'RecomputeFlag','OFF',...
    'SysBudget',SysBudget);
%% stat + all syst
[mnu4Sq{2},sin2T4{2},chi2{2},chi2_ref{2},savefile] = KSN1GridSearch('range',range,...
    'nGridSteps',nGridSteps,...
    'chi2',chi2Str,...
    'DataType',DataType,...
    'freePar',freePar,...
    'RunList',RunList,...
    'SmartGrid',SmartGrid,...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
     'SysBudget',SysBudget);
%%
for i=3:(nSys+2)
    [mnu4Sq{i},sin2T4{i},chi2{i},chi2_ref{i},savefile] = KSN1GridSearch('range',range,...
        'nGridSteps',nGridSteps,...
        'chi2',chi2Str,...
        'DataType',DataType,...
        'freePar',freePar,...
        'RunList',RunList,...
        'SmartGrid',SmartGrid,...
        'RecomputeFlag','OFF',...
        'SysEffect',mySysEffects{i-2},...
         'SysBudget',SysBudget);
end


%% plot
pHandle = cell(nSys,1);
PlotColor = {'DodgerBlue','Orange','Navy','PowderBlue','CadetBlue',...
    'YellowGreen','SeaGreen','FireBrick','DarkSlateGray',...
    'Magenta','DimGray'};


LineStyle =  {'-','-','-.',':','--','-.',':','--','-.',':','--'};
%   'Background slope'};
%% plot
for i=1:(nSys+2)
    PlotArg = {'Color',PlotColor{i},'LineStyle',LineStyle{i},'PlotSplines','ON'};
    if i>1
        PlotArg = [PlotArg,{'HoldOn','ON'}];
        hold on;
    end
    [pHandle{i},legStr] = KSN1ContourPlot(...
        'mnu4Sq',mnu4Sq{i},...
        'sin2T4',sin2T4{i},...
        'chi2',chi2{i},'chi2_ref',chi2_ref{i},...
        'CL',CL,...
        PlotArg{:});
end

%% appearance
leg = legend([pHandle{:}],DefaultSysLeg,'EdgeColor',rgb('Silver'),'Location','southwest');
if range==40
    xlim([1e-02 0.5])
elseif range>40
       xlim([2e-03 0.5])
end
ylim([1 (range+5)^2])
leg.NumColumns=2;
set(leg.BoxFace, 'ColorType','truecoloralpha', 'ColorData',uint8(255*[1;1;1;0.8]));
title(sprintf('%s , %.0f eV at %.0f%% C.L.',DataType,range,CL),'FontWeight','normal');

plotdir = [getenv('SamakPath'),'ksn1ana/LisaSterile/plots/'];
plotname = sprintf('%sStatPlus1_%s_%.0feV.png',plotdir,DataType,range);
print(gcf,plotname,'-dpng','-r400');
export_fig(gcf,strrep(plotname,'.png','.pdf'));