 RunAnaArg = {'RunNr',51645,...
        'fixPar','E0 Norm Bkg',...
        'FSDFlag','SibilleFull',...
        'ELossFlag','KatrinT2',...
        'AnaFlag','StackPixel',...
        'chi2','chi2Stat',...
        'ROIFlag','Default',...
        'SynchrotronFlag','ON',...
        'AngularTFFlag','OFF',...
        'ISCSFlag','Edep',...
        'NonPoissonScaleFactor',1,...
        'TwinBias_Q',18573.73,...
        'SysBudget',22};

R = RunAnalysis(RunAnaArg{:},'DataType','Real');
T = RunAnalysis(RunAnaArg{:},'DataType','Twin');

%%
StatData = sum(R.RunData.TBDIS);
StatTwin = sum(T.RunData.TBDIS);

RelDiffStat = 1-abs(StatData-StatTwin)/(0.5*(StatData+StatTwin))
%%

% R.exclDataStart = R.GetexclDataStart(40);
% R.Fit;

%%
