 RunAnaArg = {'RunList','KNM1',...
        'fixPar','E0 Norm Bkg',...
        'DataType','Twin',...
        'FSDFlag','SibilleFull',...
        'ELossFlag','KatrinT2',...
        'AnaFlag','StackPixel',...
        'chi2','chi2Stat',...
        'ROIFlag','Default',...
        'SynchrotronFlag','ON',...
        'AngularTFFlag','OFF',...
        'ISCSFlag','Edep',...
        'NonPoissonScaleFactor',1,...
        'TwinBias_Q',18573.70,...
        'SysBudget',22};

R = MultiRunAnalysis(RunAnaArg{:});
%%
R.exclDataStart = R.GetexclDataStart(95);
R.Fit;
