 RunAnaArg = {'RunNr',51645,...
        'fixPar','E0 Norm Bkg',...
        'DataType','Twin',...
        'FSDFlag','Sibille0p5eV',...
        'ELossFlag','KatrinT2',...
        'AnaFlag','StackPixel',...
        'chi2','chi2Stat',...
        'ROIFlag','Default',...
        'SynchrotronFlag','ON',...
        'AngularTFFlag','OFF',...
        'ISCSFlag','Edep',...
        'NonPoissonScaleFactor',1,...
        'TwinBias_Q',18573.73,...
        'SysBudget',22};

R = RunAnalysis(RunAnaArg{:});
%%
R.exclDataStart = R.GetexclDataStart(95);
R.Fit;
