% KSNX KATRIN final sensitivity
% Lisa, May 2020
% 750 days
% 130 mcps background
% TDR like systematics
%% settings for runanalysis
DataType = 'Fake';
%   
FakeInitFile = @ref_KSNX_KATRIN_Final;
RunAnaArg = {'RunNr',1,...
    'fixPar','E0 Norm Bkg',...
    'DataType','Fake',...
    'FSDFlag','SibilleFull',...
    'ELossFlag','KatrinT2A20',...
    'AnaFlag','StackPixel',...
    'chi2','chi2Stat',...
    'ROIFlag','Default',...
    'SynchrotronFlag','ON',...
    'AngularTFFlag','ON',...
    'ISCSFlag','Edep',...
    'TwinBias_Q',18573.73,...
    'SysBudget',66,...
    'pullFlag',99,...
    'NonPoissonScaleFactor',1,...
    'FakeInitFile',FakeInitFile,...
    'PixList',1:136};

T = RunAnalysis(RunAnaArg{:});
T.chi2 = 'chi2CMShape';
%% settings sterile class
SterileArg = {'RunAnaObj',T,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',50,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',40};

S = SterileAnalysis(SterileArg{:});

%%
S.LoadGridFile;
S.Interp1Grid;
S.ContourPlotOsci;
xlim([5e-03 0.5]);

%%
S.GridPlot