% Macro for test of MutliRunanalysis:R200RateErosCorrection 
% Run-wise Run Rate Correction to Build Stacked Spectrum
% T. Lasserre, Last Modified 3 May 2019

option = {...
    'DataType','Real',...
    'RunList','KNM1',...
    'exclDataStart',2,...
    'fixPar','1 5 6 7 8 9 10',...
    'chi2','chi2Stat',...
    'ELossFlag','KatrinD2',...
    'StackTolerance',0.2,...
    'NonPoissonScaleFactor',1.,...
    'Debug','ON',...
    'AnaFlag','StackPixel',...
    'PixList',[]...
    };
% No Corrections
SPR_OFF=MultiRunAnalysis(option{:},'TestRateCorr','OFF');
% Correction based on TT, HT, DT concentration & RhoD
SPR_LARA=MultiRunAnalysis(option{:},'TestRateCorr','ActivityScaling');
% EROS-based correction (cancelling correlations)
SPR_EROS=MultiRunAnalysis(option{:},'TestRateCorr','EROS');

%% Correction applied to Stack Spectrum
fig1001 = figure('Renderer','opengl');
set(fig1001,'units','normalized','pos',[0.1, 0.1,0.8,0.6]);
h1=plot(SPR_EROS.RunData.qU(2:end)-SPR_EROS.ModelObj.Q_i,SPR_OFF.RunData.TBDIS(2:end)./SPR_OFF.RunData.TBDIS(2:end),'--');
hold on
h2=plot(SPR_EROS.RunData.qU(2:end)-SPR_EROS.ModelObj.Q_i,SPR_LARA.RunData.TBDIS(2:end)./SPR_OFF.RunData.TBDIS(2:end),'s','LineWidth',2,'Color',rgb('SlateGray'),'MarkerFaceColor',rgb('Black'),'MarkerSize',8);
h3=plot(SPR_EROS.RunData.qU(2:end)-SPR_EROS.ModelObj.Q_i,SPR_EROS.RunData.TBDIS(2:end)./SPR_OFF.RunData.TBDIS(2:end),'s','LineWidth',2,'Color',rgb('Amethyst'),'MarkerFaceColor',rgb('Black'),'MarkerSize',8);
[staterror1 staterror2] = boundedline(SPR_EROS.RunData.qU(2:end)-SPR_EROS.ModelObj.Q_i,...
    SPR_EROS.RunData.TBDIS(2:end)./SPR_EROS.RunData.TBDIS(2:end),...
    1./sqrt(SPR_EROS.RunData.TBDIS(2:end)),...
    'alpha','cmap','transparency', 0.2,rgb('CadetBlue'));
hold off
xlabel(sprintf('retarding potential - %.1f (eV)',SPR_EROS.ModelObj.Q_i));
ylabel('Spectrum Correction');
legend([h2,h3,staterror2],'LARA-based Correction','EROS-based Correction','Statistical Error','Location','NorthWest')
title(sprintf('KNM1 %.0f runs (%0.f - %0.f)',SPR_EROS.nRuns,SPR_EROS.RunList(1),SPR_EROS.RunList(end)));
PrettyFigureFormat; set(gca,'FontSize',20);

%% Fit Comparison
SPR_OFF.Fit; SPR_OFF.PlotFit('Mode','Rate','saveplot','png');
SPR_EROS.Fit; SPR_EROS.PlotFit('Mode','Rate','saveplot','png');
SPR_LARA.Fit; SPR_LARA.PlotFit('Mode','Rate','saveplot','png');
