% ksn2 calculate chi2 grid search
% compare m2 free, m2 nuisance parameter
%% settings that might change
chi2 = 'chi2CMShape';
DataType = 'Real';
nGridSteps = 25;
range = 40;
%% configure RunAnalysis object
if strcmp(chi2,'chi2Stat')
    NonPoissonScaleFactor = 1;
elseif  strcmp(chi2,'chi2CMShape')
    NonPoissonScaleFactor = 1.112;
end
RunAnaArg = {'RunList','KNM2_Prompt',...
    'DataType',DataType,...
    'fixPar','E0 Norm Bkg',...%free par
    'SysBudget',40,...
    'fitter','minuit',...
    'minuitOpt','min;migrad',...
    'RadiativeFlag','ON',...
    'FSDFlag','KNM2_0p1eV',...
    'ELossFlag','KatrinT2A20',...
    'AnaFlag','StackPixel',...
    'chi2',chi2,...
    'NonPoissonScaleFactor',NonPoissonScaleFactor,...
    'FSD_Sigma',sqrt(0.0124+0.0025),...
    'TwinBias_FSDSigma',sqrt(0.0124+0.0025),...
    'TwinBias_Q',18573.7,...
    'PullFlag',99,...;%99 = no pull
    'BKG_PtSlope',3*1e-06,...
    'TwinBias_BKG_PtSlope',3*1e-06,...
    'DopplerEffectFlag','FSD'};
A = MultiRunAnalysis(RunAnaArg{:});
%% configure Sterile analysis object
SterileArg = {'RunAnaObj',A,... % Mother Object: defines RunList, Column Density, Stacking Cuts,....
    'nGridSteps',nGridSteps,...
    'SmartGrid','OFF',...
    'RecomputeFlag','OFF',...
    'SysEffect','all',...
    'RandMC','OFF',...
    'range',range};

%%
S = SterileAnalysis(SterileArg{:});
S.InterpMode = 'lin';
%%
S.PlotmNuSqOverview('PullmNuSq','OFF','SavePlot','png')
%%
S.RunAnaObj.fixPar = ConvertFixPar('freePar','mNu E0 Norm Bkg','nPar',A.nPar);
S.LoadGridFile; S.Interp1Grid;
PlotPar = S.mNuSq;

[M0,~] = contour3(S.sin2T4,S.mNu4Sq,PlotPar,[0,0]);
[M1,~] = contour3(S.sin2T4,S.mNu4Sq,PlotPar,[1,1]);
[M5,~] = contour3(S.sin2T4,S.mNu4Sq,PlotPar,[5,5]);
[Mm1,~] = contour3(S.sin2T4,S.mNu4Sq,PlotPar,[-0.5,-0.5]);
                               
%S.GridPlotFitPar('FitPar','mNuSq','Contour','ON','ContourVec',[-1,-0.5,0,1,2,10],'SavePlot','png')
hold off;
%%
close all
GetFigure;
[~,p1] = contour3(S.sin2T4,S.mNu4Sq,PlotPar,[-0.5,-0.5],'Color',rgb('Silver'),'ShowText','on','LineWidth',1.5);
hold on;
[~,~] = contour3(S.sin2T4,S.mNu4Sq,PlotPar,[1,1],'Color',rgb('Silver'),'ShowText','on','LineWidth',1.5);
[~,~] = contour3(S.sin2T4,S.mNu4Sq,PlotPar,[2,2],'Color',rgb('Silver'),'ShowText','on','LineWidth',1.5);
 [~,~] = contour3(S.sin2T4,S.mNu4Sq,PlotPar,[5,5],'Color',rgb('Silver'),'ShowText','on','LineWidth',1.5);
[~,~] = contour3(S.sin2T4,S.mNu4Sq,PlotPar,[10,10],'Color',rgb('Silver'),'ShowText','on','LineWidth',1.5);
[~,~] = contour3(S.sin2T4,S.mNu4Sq,PlotPar,[0,0],'Color',rgb('Silver'),'ShowText','on','LineWidth',1.5);
 [~,~] = contour3(S.sin2T4,S.mNu4Sq,PlotPar,[0.5,0.5],'Color',rgb('Silver'),'ShowText','on','LineWidth',1.5);

[pFree,pFix] = S.PlotmNuSqOverview('PullmNuSq','OFF','SavePlot','OFF','HoldOn','ON','BestFit','ON');
 view(2)
 grid off
 
 leg = legend([p1,pFree,pFix],...
                    sprintf('{\\itm}_\\nu^2 best fit'),...
                    sprintf('Free {\\itm}_\\nu^2 without pull term'),...   
                    sprintf('Fixed {\\itm}_\\nu^2 = 0 eV^2'),...
                    'EdgeColor',rgb('Silver'),'Location','southwest');
                PrettyLegendFormat(leg);
%% save
name_i = strrep(S.DefPlotName,'_mNuE0BkgNorm','');
plotname = sprintf('%s_mNuSqOverviewmNuSq_%.2gCL.png',name_i,S.ConfLevel);
print(gcf,plotname,'-dpng','-r450');
fprintf('save plot to %s \n',plotname);