function f = NuMassModel4parDC(p,A)

A.ComputeTBDDS(...
    'mSq_bias',p(1),...
    'E0_bias',p(2),...
    'B_bias',p(3),...
    'N_bias',p(4)); 
A.ComputeTBDIS('IStype','SuperFAST'); %
f = A.TBDIS;
end