% homogeneity of e- and b-fields in analyzing plane

savedir = sprintf('%sknm12Combi/knm12_General/results/',getenv('SamakPath'));
savename = sprintf('%sknm2_FieldsAnalyzing.mat',savedir);

if ~exist(savename,'file') 
    M2 = MultiRunAnalysis('RunList','KNM2_Prompt',...
        'NonPoissonScaleFactor',1.112,...
        'chi2','chi2Stat',...
        'BKG_PtSlope',3*1e-06,...
        'FSDFlag','KNM2_0p1eV',...
        'DopplerEffectFlag','FSD',...
        'FSD_Sigma',sqrt(0.0124+0.0025),...
        'ELossFlag','KatrinT2A20',...
        'RadiativeFlag','ON',...
        'AngularTFFlag','ON');%,...

    M2.ReadSingleRunData
    qU2 = M2.SingleRunData.qU;
    qUStd2 = mean(mean(std(qU2,0,3)'));
    
    Bana2 = M2.SingleRunData.MACE_Ba_T;
    BanaStd2 = mean(std(M2.SingleRunData.MACE_Ba_T));
    
    MakeDir(savedir);
    save(savename,'qU2','qUStd2','Bana2','BanaStd2');
else
    load(savename);
end

