M=MultiRunAnalysis('DataType','Fake','FakeRunType','FakeKITNuScan','RunList','KITNUSCAN','exclDataStart',2,'fixPar','5 6','chi2','chi2Stat','Debug','ON','ELossFlag','Abdurashitov');
M.FitRunList; 
%%
defaultEffects = struct(...
                'RF_EL','OFF',...  % Response Function(RF) EnergyLoss
                'RF_BF','OFF',...  % RF B-Fields
                'RF_RX','ON',...   % Column Density, inel cross ection
                'FSD','ON',...
                'TASR','ON',...
                'TCoff_RAD','ON',...
                'TCoff_OTHER','OFF',...
                'DOPoff','OFF');
M.ComputeCM('RecomputeFlag','OFF','Stack','ON','WGTS_TASR_RelErr',1e-3,'SysEffects',defaultEffects,'BkgCM','ON');
M.Fit; M.PlotFit('Mode','Rate');