%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                        ANALYZE KIT NU SCAN                            %%
%%                                                                       %%
%%                      T. Lasserre, 11/03/2019                          %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SPR=MultiRunAnalysis(...
    'DataType','Real',...
    'RunList','KITNUSCAN',...
    'exclDataStart',2,...
    'fixPar','1 5 6',...
    'chi2','chi2CMShape',...
    'ELossFlag','KatrinD2',...
    'StackTolerance',0.2,...
    'NonPoissonScaleFactor',1.5,...
    'Debug','ON');

SPR.chi2='chi2Stat';
%SPR.FitRunList('Recompute','OFF')
%SPR.FitRunList_SlowControl
 
%% Systematics
SPR.chi2='chi2CMShape';
systematics = struct(...
    'RF_EL','ON',...
    'RF_BF','ON',...
    'RF_RX','ON',...
    'FSD','ON',...
    'TASR','ON',...
    'TCoff_RAD','ON',...
    'TCoff_OTHER','ON',...
    'DOPoff','OFF');
CMoptions   = {
    'WGTS_TASR_RelErr',0.005,...
    'FSDNorm_RelErr',0.01,...
    'FSDShapeGS_RelErr',0.04,...
    'FSDShapeES_RelErr',0.18,...
    'MACE_Ba_T_RelErr',0.01,...
    'MACE_Bmax_T_RelErr',0.002,...
    'WGTS_B_T_RelErr',0.025,...
    'WGTS_CD_MolPerCm2_RelErr',0.08,...
    'ISXsection_RelErr',0.02,...
    'BkgCM','ON',...
    'Stack','ON'...
    };
SPR.ComputeCM('RecomputeFlag','OFF','SysEffects',systematics,CMoptions{:});
%SPR.chi2='chi2Stat';

%% Fit
SPR.Fit('CATS','OFF');
SPR.PlotFit('Mode','Rate','saveplot','png')

%% qU Scan
%SPR.qUScan

%% PlotDataModel
%SPR.PlotDataModel_KNM1