RunAnaArg = {'RunNr',56160,...
    'DataType','Twin',...
    'fixPar','mNu E0 Norm Bkg',...
    'minuitOpt','min ; minos',...
    'ELossFlag','KatrinT2A20',...
    'SysBudget',40,...
    'AnaFlag','StackPixel',...
    'chi2','chi2Stat',...
    'TwinBias_Q',18573.7,...
    'NonPoissonScaleFactor',1,...
    'FSD_Sigma',0.13,...
    'TwinBias_FSDSigma',0.13,...
    'RingMerge','Full',...
    'PullFlag',99,...
    'BKG_PtSlope',0,...
    'TwinBias_BKG_PtSlope',0,...
    'TwinBias_Time',7416*30};

T1 = RunAnalysis(RunAnaArg{:},'FSDFlag','KNM2','exclDataStart',11);
tic; T1.Fit;toc;
T2 = RunAnalysis(RunAnaArg{:},'FSDFlag','KNM2_0p5eV','exclDataStart',11);
tic; T2.Fit; toc;
T3 = RunAnalysis(RunAnaArg{:},'FSDFlag','KNM2_0p1eV','exclDataStart',11);
tic;  T3.Fit;toc;
    
    